-- ISOLATED TEST DATABASE ONLY; do not run these fixtures in the production SQL Editor.
begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(37);
select public.configure_private_owner('owner-test@example.com');
insert into auth.users(id,email,aud,role,email_confirmed_at,created_at,updated_at) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','owner-test@example.com','authenticated','authenticated',now(),now(),now());
select has_table('public','vocabulary','Private vocabulary exists');
select has_table('public','review_items','Unified review scheduler exists');
select has_table('public','review_logs','Immutable review history exists');
select has_table('public','reading_progress','Cross-device reading progress exists');
select has_table('public','mistakes','Long-term mistake memory exists');
select has_table('public','personal_audio_files','Private cross-device audio metadata exists');
select throws_ok($$insert into auth.users(id,email) values('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','outsider@example.com')$$,'P0001','Private application: registration is closed','Other account registration is blocked');
set local role anon;
select throws_ok($$select * from public.grammar$$,'42501',null,'Anonymous role cannot read private content');
select throws_ok($$select public.claim_ai_request('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee')$$,'42501',null,'Anonymous role cannot claim an AI request');
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","email":"owner-test@example.com","role":"authenticated"}',true);
select ok(public.is_private_owner(),'Configured owner is recognized');
select is((public.claim_ai_request('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee')->>'acquired')::boolean,true,'Owner acquires a new AI request');
select is((public.claim_ai_request('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee')->>'acquired')::boolean,false,'Duplicate AI request in the same transaction is not reacquired');
select throws_ok($$select public.claim_ai_request(null)$$,'22023','Invalid AI request','Null AI request IDs are rejected explicitly');
insert into public.vocabulary(id,user_id,language_code,term) values('cccccccc-cccc-4ccc-8ccc-cccccccccccc','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','ja','余裕');
select is((select count(*)::int from public.review_items where item_id='cccccccc-cccc-4ccc-8ccc-cccccccccccc'),1,'New vocabulary enters unified SRS');
select public.record_review((select id from public.review_items where item_id='cccccccc-cccc-4ccc-8ccc-cccccccccccc'),'dddddddd-dddd-4ddd-8ddd-dddddddddddd','good',now()-interval '10 seconds');
select public.record_review((select id from public.review_items where item_id='cccccccc-cccc-4ccc-8ccc-cccccccccccc'),'dddddddd-dddd-4ddd-8ddd-dddddddddddd','good',now()-interval '10 seconds');
select is((select count(*)::int from public.review_logs),1,'Retried review event is not duplicated');
select is((select review_count from public.review_items where item_id='cccccccc-cccc-4ccc-8ccc-cccccccccccc'),1,'Retried review does not increase count');
select throws_ok($$select public.record_review((select id from public.review_items where item_id='cccccccc-cccc-4ccc-8ccc-cccccccccccc'),'dddddddd-dddd-4ddd-8ddd-dddddddddddd','easy',now()-interval '10 seconds')$$,'22023','Review event ID reused with a different payload','An event ID cannot be reused for a different rating');
select throws_ok($$select public.sync_personal_state(null,'invalid-revision','{"version":2}'::jsonb)$$,'22023','Invalid state','A null revision cannot bypass compare-and-swap');
select is((select interval_days from public.review_items where item_id='cccccccc-cccc-4ccc-8ccc-cccccccccccc'),1,'First Good schedules one day');
select is((public.due_review_counts('ja')->>'vocabulary')::int,0,'AI due counts exclude future reviews');
select throws_ok($$select public.due_review_counts(null)$$,'42501','Private owner and valid language required','Null language is rejected');
select throws_ok($$select private.project_state(auth.uid(),'{}'::jsonb)$$,'42501',null,'Browser cannot call the private projection directly');
select throws_ok($$update public.review_items set due_at=now()$$,'42501',null,'Client cannot overwrite scheduler fields');
select public.sync_personal_state(0,'fixture-1','{"version":2,"profile":{"name":"Owner","language":"ja","dailyGoal":20},"reviews":{},"dictionary":{},"reviewHistory":[],"sentences":[],"sessions":[],"_clock":{},"_deleted":{}}'::jsonb);
select is((select revision::int from public.user_progress),1,'Initial sync advances revision');
select is((public.sync_personal_state(0,'fixture-1','{"version":2,"profile":{"name":"Owner","language":"ja","dailyGoal":20},"reviews":{},"dictionary":{},"reviewHistory":[],"sentences":[],"sessions":[],"_clock":{},"_deleted":{}}'::jsonb)->>'revision')::int,1,'Repeated sync batch remains idempotent');
select is((public.sync_personal_state(0,'fixture-stale','{"version":2,"profile":{"name":"Owner","language":"ja","dailyGoal":20},"reviews":{},"dictionary":{},"reviewHistory":[],"sentences":[],"sessions":[],"_clock":{},"_deleted":{}}'::jsonb)->>'applied')::boolean,false,'Stale revision returns a merge conflict');
select public.sync_personal_state(1,'fixture-audio','{"version":2,"profile":{"name":"Owner","language":"ja","dailyGoal":20},"reviews":{},"dictionary":{},"reviewHistory":[],"sentences":[],"sessions":[],"_clock":{},"_deleted":{},"audioFiles":{"audio-ja":{"language":"ja","title":"New recording","storagePath":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa/audio-ja/recording-new","mimeType":"audio/mpeg","size":500,"updatedAt":2000}},"listeningPositions":{"audio-ja":{"offset":42,"progress":67,"mediaId":"recording-new","updatedAt":3000}}}'::jsonb);
select is((select media_id from public.listening_progress where user_id=auth.uid()),'recording-new','Listening position retains recording identity');
select is((select extract(epoch from source_updated_at)::int from public.personal_audio_files where user_id=auth.uid()),2,'Audio replacement keeps selection time instead of sync time');
select throws_ok($$insert into public.personal_audio_files(user_id,client_id,language_code,title,storage_path,mime_type,byte_count) values(auth.uid(),'bad-path','ja','Blocked','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/audio','audio/mpeg',1)$$,'23514',null,'Audio path must belong to the row owner');
select public.sync_personal_state(2,'fixture-audio-replacement','{"version":2,"profile":{"name":"Owner","language":"ja","dailyGoal":20},"reviews":{},"dictionary":{},"reviewHistory":[],"sentences":[],"sessions":[],"_clock":{},"_deleted":{},"audioFiles":{"audio-ja":{"language":"ja","title":"Replacement recording","storagePath":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa/audio-ja/replacement","mimeType":"audio/mpeg","size":600,"updatedAt":4000}},"listeningPositions":{"audio-ja":{"offset":0,"progress":0,"mediaId":"replacement","updatedAt":5000}}}'::jsonb);
select is((select media_id from public.listening_progress where user_id=auth.uid()),'replacement','Replacement listening position belongs to the new recording');
select is((select position_seconds::int from public.listening_progress where user_id=auth.uid()),0,'New recording starts at its own position');
select is((select extract(epoch from source_updated_at)::int from public.personal_audio_files where user_id=auth.uid()),4,'Selection time updates on replacement without using server time');
select set_config('request.jwt.claims','{"sub":"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb","email":"outsider@example.com","role":"authenticated"}',true);
select throws_ok($$select public.claim_ai_request('ffffffff-ffff-4fff-8fff-ffffffffffff')$$,'42501','Private owner required','Non-owner cannot claim an AI request');
select is((select count(*)::int from public.vocabulary),0,'Another authenticated identity cannot read private vocabulary');
select is((select count(*)::int from public.profiles),0,'Another authenticated identity cannot read private profile');
select throws_ok($$select public.due_review_counts('ja')$$,'42501','Private owner and valid language required','Non-owner cannot obtain due counts');
select throws_ok($$select public.export_personal_archive()$$,'42501','Private owner required','Non-owner cannot export the archive');
select * from finish();
rollback;
