-- ISOLATED TEST DATABASE ONLY; do not run account fixtures in production.
begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(22);
select public.configure_private_owner('phase-one-owner@example.com');
insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data,aud,role,created_at,updated_at)
values('11111111-1111-4111-8111-111111111111','phase-one-owner@example.com',now(),'{"name":"Private owner"}','authenticated','authenticated',now(),now());
select throws_ok($$insert into auth.users(id,email,email_confirmed_at) values('22222222-2222-4222-8222-222222222222','phase-one-owner@example.com',now())$$,'P0001','Private application: registration is closed','A second Auth UUID cannot claim the pinned owner email');
select ok((select relrowsecurity from pg_class where oid='public.profiles'::regclass),'Profile has RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.user_languages'::regclass),'Language profiles have RLS enabled');
select is((select count(*)::int from pg_policies where schemaname='public' and (qual='true' or with_check='true')),0,'No public learning table has a universally permissive policy');
set local role anon;
select throws_ok($$select * from public.profiles$$,'42501',null,'Anonymous cannot read profiles');
select throws_ok($$select * from public.user_languages$$,'42501',null,'Anonymous cannot read language profiles');
select throws_ok($$select public.get_private_account()$$,'42501',null,'Anonymous cannot execute account RPC');
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"11111111-1111-4111-8111-111111111111","email":"phase-one-owner@example.com","role":"authenticated"}',true);
select ok(public.is_private_owner(),'Confirmed pinned owner is accepted');
select is(public.get_private_account()#>>'{profile,id}','11111111-1111-4111-8111-111111111111','Account RPC returns the same owner identity');
select is(jsonb_array_length(public.get_private_account()->'languages'),2,'English and Japanese profiles are provisioned');
select is((public.get_private_account()#>>'{profile,daily_goal_minutes}')::int,20,'Daily goal starts at twenty minutes');
select throws_ok($$insert into public.profiles(id) values('22222222-2222-4222-8222-222222222222')$$,'42501',null,'Owner cannot insert a profile for another user');
select throws_ok($$update public.user_languages set user_id='22222222-2222-4222-8222-222222222222'$$,'42501',null,'Language row ownership cannot be changed');
select throws_ok($$update public.user_languages set current_level='N3' where language_code='en'$$,'23514',null,'English cannot use a Japanese level');
select throws_ok($$update public.user_languages set primary_language=true where language_code='en'$$,'23505',null,'Only one primary language is allowed');
select throws_ok($$select private.ensure_private_profile(auth.uid())$$,'42501',null,'Browser cannot invoke account provisioning');
select throws_ok($$select public.configure_private_owner('other@example.com')$$,'42501',null,'Browser cannot change the whitelist');
reset role;
update auth.users set email_confirmed_at=null where id='11111111-1111-4111-8111-111111111111';
set local role authenticated;
select ok(not public.is_private_owner(),'Cached verified JWT cannot bypass a currently unconfirmed Auth account');
select throws_ok($$select public.get_private_account()$$,'42501','Private owner required','Unconfirmed owner cannot load a private account');
select set_config('request.jwt.claims','{"sub":"22222222-2222-4222-8222-222222222222","email":"phase-one-owner@example.com","role":"authenticated"}',true);
select ok(not public.is_private_owner(),'Matching email alone cannot bypass pinned user ID');
select is((select count(*)::int from public.user_languages),0,'Another identity cannot read language data');
select throws_ok($$select public.get_private_account()$$,'42501',null,'Another identity cannot execute the private account loader');
select * from finish();
rollback;
