-- ISOLATED TEST DATABASE ONLY: never run owner fixture setup in production.
begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(21);
select is((select count(*)::int from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p') and not c.relrowsecurity),0,'Every application table has RLS');
select is((select count(*)::int from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p') and has_table_privilege('anon',c.oid,'SELECT')),0,'Anonymous has no direct application table reads');
select is((select count(*)::int from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p') and has_table_privilege('authenticated',c.oid,'TRUNCATE')),0,'Browser cannot bypass RLS with TRUNCATE');
select is((select count(*)::int from storage.buckets where id in ('personal-audio','personal-backups','personal-content') and not public),3,'All managed storage buckets are private');
select is((select count(*)::int from pg_policy where polrelid='storage.objects'::regclass and not polpermissive and polname in ('managed_storage_owner_fence','managed_storage_anon_fence')),2,'Storage fences cannot be widened by permissive policies');
select is((select count(*)::int from pg_policy p join pg_class c on c.oid=p.polrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and p.polname='private_owner_fence' and not p.polpermissive),42,'Every browser-readable table has a restrictive owner fence');
select is((select count(*)::int from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('review_items','review_logs','user_progress','sync_batches','client_id_map','ai_requests') and (has_table_privilege('authenticated',c.oid,'INSERT') or has_table_privilege('authenticated',c.oid,'UPDATE') or has_table_privilege('authenticated',c.oid,'DELETE'))),0,'Review events and synchronization state can only change through RPCs');
select has_index('public','legacy_profiles','legacy_profiles_pkey','Old profile index is preserved under a non-conflicting name');
select has_index('public','profiles','profiles_pkey','New profile primary key exists');
select public.configure_private_owner('permissions-owner@example.com');
insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data,aud,role,created_at,updated_at)
values('33333333-3333-4333-8333-333333333333','permissions-owner@example.com',now(),'{}','authenticated','authenticated',now(),now());
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"33333333-3333-4333-8333-333333333333","email":"permissions-owner@example.com","role":"authenticated"}',true);
insert into public.vocabulary(id,user_id,language_code,term) values('44444444-4444-4444-8444-444444444444',auth.uid(),'ja','余裕');
select throws_ok($$update public.vocabulary set user_id='55555555-5555-4555-8555-555555555555' where id='44444444-4444-4444-8444-444444444444'$$,'42501',null,'Owner cannot transfer vocabulary to another UID');
select throws_ok($$insert into public.review_logs default values$$,'42501',null,'Review history cannot be appended by the browser');
insert into public.vocabulary_examples(vocabulary_id,sentence) values('44444444-4444-4444-8444-444444444444','時間に余裕があります。');
select is((select count(*)::int from public.vocabulary_examples),1,'Owner can add an example to an owned word');
select throws_ok($$insert into public.vocabulary_examples(vocabulary_id,sentence) values('55555555-5555-4555-8555-555555555555','Blocked example')$$,'42501',null,'A child cannot reference an unowned parent');
select throws_ok($$truncate public.vocabulary cascade$$,'42501',null,'TRUNCATE is denied to the browser role');
insert into public.vocabulary(id,user_id,language_code,term) values('66666666-6666-4666-8666-666666666666',auth.uid(),'ja','保存テスト');
insert into public.mistakes(id,user_id,language_code,area,pattern,vocabulary_id) values('77777777-7777-4777-8777-777777777777',auth.uid(),'ja','vocabulary','retained mistake','66666666-6666-4666-8666-666666666666');
delete from public.vocabulary where id='66666666-6666-4666-8666-666666666666';
select ok(exists(select 1 from public.mistakes where id='77777777-7777-4777-8777-777777777777' and vocabulary_id is null and user_id=auth.uid()),'Deleting vocabulary retains the mistake and its user ownership');
reset role;
select throws_ok($$insert into public.user_progress(user_id,state) values('33333333-3333-4333-8333-333333333333','null'::jsonb)$$,'P0001','Invalid personal snapshot','JSON null cannot be stored as a personal snapshot');
select throws_ok($$insert into public.user_progress(user_id,state) values('33333333-3333-4333-8333-333333333333','{"version":2}'::jsonb)$$,'P0001','Invalid personal snapshot','Incomplete snapshot cannot be stored');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"55555555-5555-4555-8555-555555555555","email":"permissions-owner@example.com","role":"authenticated"}',true);
select is((select count(*)::int from public.vocabulary_examples),0,'Spoofed email with another UID cannot read children');
select throws_ok($$insert into public.vocabulary_collocations(vocabulary_id,collocation) values('44444444-4444-4444-8444-444444444444','時間に余裕がある')$$,'42501',null,'Another UID cannot attach a collocation to the owner word');
select is((with changed as (update public.vocabulary set notes='unauthorized' returning id) select count(*)::int from changed),0,'Another UID cannot update owner vocabulary');
select is((with changed as (delete from public.vocabulary returning id) select count(*)::int from changed),0,'Another UID cannot delete owner vocabulary');
select * from finish();
rollback;
