-- Read-only verification after 005 succeeds, as postgres. No RPCs or test writes.
with expected(t) as (select unnest(array['ai_conversations','ai_messages','ai_requests','ai_usage','articles','backups','client_id_map','courses','daily_plans','downloads','grammar','grammar_examples','grammar_relations','languages','legacy_ai_conversations','legacy_grammar','legacy_profiles','legacy_reviews','legacy_study_sessions','legacy_vocabulary','lessons','listening_episodes','listening_progress','mistakes','personal_notes','profiles','reading_progress','review_items','review_logs','saved_sentences','sentence_grammar','sentence_vocabulary','speaking_sessions','study_sessions','sync_batches','user_grammar_progress','user_languages','user_progress','users','vocabulary','vocabulary_collocations','vocabulary_examples'])), tables as (
 select e.t,c.oid,c.relrowsecurity from expected e left join pg_catalog.pg_namespace n on n.nspname='public' left join pg_catalog.pg_class c on c.relnamespace=n.oid and c.relname=e.t and c.relkind='r'
), ledger as (select m.statements[3]::jsonb as before_rows,m.statements[4]::jsonb as hashes from supabase_migrations.schema_migrations m where m.version='005'), stored_rows as (
 select 'ai_conversations' as t,'public.ai_conversations'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.ai_conversations x
 union all select 'ai_messages' as t,'public.ai_messages'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.ai_messages x
 union all select 'ai_requests' as t,'public.ai_requests'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.ai_requests x
 union all select 'ai_usage' as t,'public.ai_usage'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.ai_usage x
 union all select 'articles' as t,'public.articles'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.articles x
 union all select 'backups' as t,'public.backups'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.backups x
 union all select 'client_id_map' as t,'public.client_id_map'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.client_id_map x
 union all select 'courses' as t,'public.courses'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.courses x
 union all select 'daily_plans' as t,'public.daily_plans'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.daily_plans x
 union all select 'downloads' as t,'public.downloads'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.downloads x
 union all select 'grammar' as t,'public.grammar'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.grammar x
 union all select 'grammar_examples' as t,'public.grammar_examples'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.grammar_examples x
 union all select 'grammar_relations' as t,'public.grammar_relations'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.grammar_relations x
 union all select 'languages' as t,'public.languages'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.languages x
 union all select 'legacy_ai_conversations' as t,'public.legacy_ai_conversations'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.legacy_ai_conversations x
 union all select 'legacy_grammar' as t,'public.legacy_grammar'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.legacy_grammar x
 union all select 'legacy_profiles' as t,'public.legacy_profiles'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.legacy_profiles x
 union all select 'legacy_reviews' as t,'public.legacy_reviews'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.legacy_reviews x
 union all select 'legacy_study_sessions' as t,'public.legacy_study_sessions'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.legacy_study_sessions x
 union all select 'legacy_vocabulary' as t,'public.legacy_vocabulary'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.legacy_vocabulary x
 union all select 'lessons' as t,'public.lessons'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.lessons x
 union all select 'listening_episodes' as t,'public.listening_episodes'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.listening_episodes x
 union all select 'listening_progress' as t,'public.listening_progress'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.listening_progress x
 union all select 'mistakes' as t,'public.mistakes'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.mistakes x
 union all select 'personal_notes' as t,'public.personal_notes'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.personal_notes x
 union all select 'profiles' as t,'public.profiles'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.profiles x
 union all select 'reading_progress' as t,'public.reading_progress'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.reading_progress x
 union all select 'review_items' as t,'public.review_items'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.review_items x
 union all select 'review_logs' as t,'public.review_logs'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.review_logs x
 union all select 'saved_sentences' as t,'public.saved_sentences'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.saved_sentences x
 union all select 'sentence_grammar' as t,'public.sentence_grammar'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.sentence_grammar x
 union all select 'sentence_vocabulary' as t,'public.sentence_vocabulary'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.sentence_vocabulary x
 union all select 'speaking_sessions' as t,'public.speaking_sessions'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.speaking_sessions x
 union all select 'study_sessions' as t,'public.study_sessions'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.study_sessions x
 union all select 'sync_batches' as t,'public.sync_batches'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.sync_batches x
 union all select 'user_grammar_progress' as t,'public.user_grammar_progress'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.user_grammar_progress x
 union all select 'user_languages' as t,'public.user_languages'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.user_languages x
 union all select 'user_progress' as t,'public.user_progress'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.user_progress x
 union all select 'users' as t,'public.users'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.users x
 union all select 'vocabulary' as t,'public.vocabulary'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.vocabulary x
 union all select 'vocabulary_collocations' as t,'public.vocabulary_collocations'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.vocabulary_collocations x
 union all select 'vocabulary_examples' as t,'public.vocabulary_examples'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),'[]'::jsonb)::text) as content_md5 from public.vocabulary_examples x
), problems(kind,detail) as (
 select 'missing_table',t.t from tables t where t.oid is null
 union all select 'rls_disabled',t.t from tables t where t.oid is not null and not t.relrowsecurity
 union all select 'unexpected_table',c.relname::text from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p') and not exists(select 1 from expected e where e.t=c.relname)
 union all select 'browser_table_privilege',t.t||':'||r.role_name||':'||p.privilege from tables t cross join (values('anon'),('authenticated')) r(role_name)
  cross join (values('SELECT'),('INSERT'),('UPDATE'),('DELETE'),('TRUNCATE'),('REFERENCES'),('TRIGGER')) p(privilege) where t.oid is not null and has_table_privilege(r.role_name,t.oid,p.privilege)
 union all select 'old_constraint_remains',c.conname from pg_catalog.pg_constraint c where (c.conrelid='public.user_progress'::regclass and c.conname='user_progress_state_check') or (c.conrelid='public.mistakes'::regclass and c.conname='mistakes_vocabulary_id_user_id_fkey')
 union all select 'invalid_snapshot_bound','bounded_personal_snapshot' where not exists(select 1 from pg_catalog.pg_constraint c where c.conrelid='public.user_progress'::regclass and c.conname='bounded_personal_snapshot' and c.contype='c' and c.convalidated and position('octet_length' in pg_get_constraintdef(c.oid))>0 and position('16777216' in pg_get_constraintdef(c.oid))>0)
 union all select 'invalid_mistake_ownership_fk','mistakes_vocabulary_owner' where not exists(select 1 from pg_catalog.pg_constraint c where c.conrelid='public.mistakes'::regclass and c.conname='mistakes_vocabulary_owner' and c.contype='f' and c.convalidated and c.confrelid='public.vocabulary'::regclass and (select array_agg(a.attname::text order by k.ord) from unnest(c.conkey) with ordinality k(num,ord) join pg_catalog.pg_attribute a on a.attrelid=c.conrelid and a.attnum=k.num)=array['vocabulary_id','user_id'] and (select array_agg(a.attname::text order by k.ord) from unnest(c.confkey) with ordinality k(num,ord) join pg_catalog.pg_attribute a on a.attrelid=c.confrelid and a.attnum=k.num)=array['id','user_id']
  and c.confdeltype='n' and c.confdelsetcols=array[(select a.attnum from pg_catalog.pg_attribute a where a.attrelid=c.conrelid and a.attname='vocabulary_id')]::smallint[])
 union all select 'invalid_validator','private.validate_personal_snapshot()' where not exists(select 1 from pg_catalog.pg_proc p join pg_catalog.pg_language l on l.oid=p.prolang where p.oid=to_regprocedure('private.validate_personal_snapshot()') and not p.prosecdef and pg_get_userbyid(p.proowner)='postgres' and l.lanname='plpgsql'
  and exists(select 1 from unnest(p.proconfig) s where split_part(s,'=',1)='search_path' and trim(split_part(s,'=',2),E' \'"')=''))
 union all select 'validator_browser_execute',r.role_name from (values('anon'),('authenticated')) r(role_name) where to_regprocedure('private.validate_personal_snapshot()') is not null and has_function_privilege(r.role_name,to_regprocedure('private.validate_personal_snapshot()'),'EXECUTE')
 union all select 'invalid_validator_trigger','user_progress.validate_personal_snapshot' where not exists(select 1 from pg_catalog.pg_trigger g where g.tgrelid='public.user_progress'::regclass and g.tgname='validate_personal_snapshot' and g.tgfoid=to_regprocedure('private.validate_personal_snapshot()') and g.tgtype=23 and g.tgenabled='O'
  and (select array_agg(x.num order by x.ord) from unnest(g.tgattr::smallint[]) with ordinality x(num,ord))=array[(select a.attnum from pg_catalog.pg_attribute a where a.attrelid=g.tgrelid and a.attname='state')]::smallint[])
)
select jsonb_build_object(
 'migration_versions',(select jsonb_agg(m.version order by m.version) from supabase_migrations.schema_migrations m),
 'migration_005_recorded',exists(select 1 from supabase_migrations.schema_migrations m where m.version='005' and m.name='hardening_and_projection'),
 'expected_tables',42,'found_tables',(select count(*) from tables t where t.oid is not null),
 'problems',coalesce((select jsonb_agg(jsonb_build_object('check',p.kind,'detail',p.detail) order by p.kind,p.detail) from problems p),'[]'::jsonb),
 'existing_tables_and_data_preserved',coalesce((select jsonb_object_agg(s.t,jsonb_build_object('oid',s.oid,'rows',s.rows,'content_md5',s.content_md5)) from stored_rows s)=(select l.before_rows from ledger l),false),
 'prior_functions_unchanged',coalesce(md5((select jsonb_agg(to_jsonb(p) order by p.oid) from pg_catalog.pg_proc p where p.oid in (select to_regprocedure(s) from unnest(array['public.create_user_profile()','public.configure_private_owner(text)','public.is_private_owner()','public.consume_ai_request(uuid)','private.guard_owner_signup()','private.touch_updated_at()','public.record_review(uuid,uuid,text,timestamptz,integer)','public.sync_personal_state(bigint,text,jsonb)','public.personal_progress(text)','private.resolve_id(uuid,text,text)','private.validate_review_target()','private.create_review_item()','private.create_grammar_review()','private.project_state(uuid,jsonb)','public.claim_ai_request(uuid)']) s))::text)=(select l.hashes->>'functions' from ledger l),false),
 'prior_policies_unchanged',coalesce(md5((select jsonb_agg(to_jsonb(p) order by p.schemaname,p.tablename,p.policyname) from pg_catalog.pg_policies p where p.schemaname='public' or (p.schemaname='storage' and p.tablename='objects'))::text)=(select l.hashes->>'policies' from ledger l),false),
 'prior_app_triggers_unchanged',coalesce(md5((select jsonb_agg(to_jsonb(g) order by g.oid) from pg_catalog.pg_trigger g join pg_catalog.pg_class c on c.oid=g.tgrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where not g.tgisinternal and (n.nspname='public' or g.tgrelid='auth.users'::regclass) and not (g.tgrelid='public.user_progress'::regclass and g.tgname='validate_personal_snapshot'))::text)=(select l.hashes->>'triggers' from ledger l),false),
 'validator_unchanged',coalesce(md5((select to_jsonb(p) from pg_catalog.pg_proc p where p.oid=to_regprocedure('private.validate_personal_snapshot()'))::text)=(select l.hashes->>'validator' from ledger l),false),
 'constraints_unchanged',coalesce(md5((select jsonb_agg(to_jsonb(c) order by c.oid) from pg_catalog.pg_constraint c where (c.conrelid='public.user_progress'::regclass and c.conname='bounded_personal_snapshot') or (c.conrelid='public.mistakes'::regclass and c.conname='mistakes_vocabulary_owner'))::text)=(select l.hashes->>'constraints' from ledger l),false),
 'snapshot_limit_bytes',16777216,
 'mistake_user_id_not_null',(select a.attnotnull from pg_catalog.pg_attribute a where a.attrelid='public.mistakes'::regclass and a.attname='user_id'),
 'owner_configured',(select count(*)=1 and bool_and(o.email='owner@example.com') from private.app_owner o),
 'owner_table_rls',(select c.relrowsecurity from pg_catalog.pg_class c where c.oid='private.app_owner'::regclass),
 'browser_private_schema_access',has_schema_privilege('anon','private','USAGE') or has_schema_privilege('authenticated','private','USAGE'),
 'browser_owner_table_access',exists(select 1 from (values('anon'),('authenticated')) r(role_name) cross join (values('SELECT'),('INSERT'),('UPDATE'),('DELETE'),('TRUNCATE'),('REFERENCES'),('TRIGGER')) p(privilege) where has_table_privilege(r.role_name,'private.app_owner',p.privilege)),
 'private_buckets',(select count(*) from storage.buckets b where b.id in ('personal-audio','personal-backups','personal-content') and not b.public),
 'auth_profile_trigger_present',exists(select 1 from pg_catalog.pg_trigger g where g.tgrelid='auth.users'::regclass and g.tgname='on_auth_user_created' and g.tgfoid=to_regprocedure('public.create_user_profile()') and g.tgtype=5 and g.tgenabled='O'),
 'signup_guard_present',exists(select 1 from pg_catalog.pg_trigger g where g.tgrelid='auth.users'::regclass and g.tgname='allow_private_owner_only' and g.tgfoid=to_regprocedure('private.guard_owner_signup()') and g.tgtype=7 and g.tgenabled='O'),
 'storage_rls',(select c.relrowsecurity from pg_catalog.pg_class c where c.oid='storage.objects'::regclass),
 'ledger_rls',(select c.relrowsecurity from pg_catalog.pg_class c where c.oid='supabase_migrations.schema_migrations'::regclass),
 'browser_ledger_schema_access',has_schema_privilege('anon','supabase_migrations','USAGE') or has_schema_privilege('authenticated','supabase_migrations','USAGE'),
 'rls_helper_unchanged',coalesce((select md5(to_jsonb(p)::text) from pg_catalog.pg_proc p where p.oid=to_regprocedure('public.rls_auto_enable()'))=(select substring(m.statements[2] from 'helper_catalog_md5=([a-f0-9]{32})') from supabase_migrations.schema_migrations m where m.version='005'),false),
 'ensure_rls_unchanged',coalesce((select md5(to_jsonb(e)::text) from pg_catalog.pg_event_trigger e where e.evtname='ensure_rls')=(select substring(m.statements[2] from 'ensure_rls_catalog_md5=([a-f0-9]{32})') from supabase_migrations.schema_migrations m where m.version='005'),false)
) as migration_005_verification;
