-- Read-only verification of 007, as postgres. No RPCs, writes or role/JWT changes.
with expected(t) as (select unnest(array['ai_conversations','ai_messages','ai_requests','ai_usage','articles','backups','client_id_map','courses','daily_plans','downloads','grammar','grammar_examples','grammar_relations','languages','legacy_ai_conversations','legacy_grammar','legacy_profiles','legacy_reviews','legacy_study_sessions','legacy_vocabulary','lessons','listening_episodes','listening_progress','mistakes','personal_audio_files','personal_notes','profiles','reading_progress','review_items','review_logs','saved_sentences','sentence_grammar','sentence_vocabulary','speaking_sessions','study_sessions','sync_batches','user_grammar_progress','user_languages','user_progress','users','vocabulary','vocabulary_collocations','vocabulary_examples'])), tables as (
 select e.t,c.oid,c.relrowsecurity from expected e left join pg_catalog.pg_namespace n on n.nspname='public' left join pg_catalog.pg_class c on c.relnamespace=n.oid and c.relname=e.t and c.relkind='r'
), ledger as (select m.statements[3]::jsonb as before_rows,m.statements[4]::jsonb as hashes from supabase_migrations.schema_migrations m where m.version='007'), stored_rows as (
 select 'ai_conversations' as t,'public.ai_conversations'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.ai_conversations x
 union all select 'ai_messages' as t,'public.ai_messages'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.ai_messages x
 union all select 'ai_requests' as t,'public.ai_requests'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.ai_requests x
 union all select 'ai_usage' as t,'public.ai_usage'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.ai_usage x
 union all select 'articles' as t,'public.articles'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.articles x
 union all select 'backups' as t,'public.backups'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.backups x
 union all select 'client_id_map' as t,'public.client_id_map'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.client_id_map x
 union all select 'courses' as t,'public.courses'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.courses x
 union all select 'daily_plans' as t,'public.daily_plans'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.daily_plans x
 union all select 'downloads' as t,'public.downloads'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.downloads x
 union all select 'grammar' as t,'public.grammar'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.grammar x
 union all select 'grammar_examples' as t,'public.grammar_examples'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.grammar_examples x
 union all select 'grammar_relations' as t,'public.grammar_relations'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.grammar_relations x
 union all select 'languages' as t,'public.languages'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.languages x
 union all select 'legacy_ai_conversations' as t,'public.legacy_ai_conversations'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.legacy_ai_conversations x
 union all select 'legacy_grammar' as t,'public.legacy_grammar'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.legacy_grammar x
 union all select 'legacy_profiles' as t,'public.legacy_profiles'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.legacy_profiles x
 union all select 'legacy_reviews' as t,'public.legacy_reviews'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.legacy_reviews x
 union all select 'legacy_study_sessions' as t,'public.legacy_study_sessions'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.legacy_study_sessions x
 union all select 'legacy_vocabulary' as t,'public.legacy_vocabulary'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.legacy_vocabulary x
 union all select 'lessons' as t,'public.lessons'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.lessons x
 union all select 'listening_episodes' as t,'public.listening_episodes'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.listening_episodes x
 union all select 'listening_progress' as t,'public.listening_progress'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x)-'media_id' order by (to_jsonb(x)-'media_id')::text),'[]'::jsonb)::text) as content_md5 from public.listening_progress x
 union all select 'mistakes' as t,'public.mistakes'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.mistakes x
 union all select 'personal_audio_files' as t,'public.personal_audio_files'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x)-'source_updated_at' order by (to_jsonb(x)-'source_updated_at')::text),'[]'::jsonb)::text) as content_md5 from public.personal_audio_files x
 union all select 'personal_notes' as t,'public.personal_notes'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.personal_notes x
 union all select 'profiles' as t,'public.profiles'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.profiles x
 union all select 'reading_progress' as t,'public.reading_progress'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.reading_progress x
 union all select 'review_items' as t,'public.review_items'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.review_items x
 union all select 'review_logs' as t,'public.review_logs'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.review_logs x
 union all select 'saved_sentences' as t,'public.saved_sentences'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.saved_sentences x
 union all select 'sentence_grammar' as t,'public.sentence_grammar'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.sentence_grammar x
 union all select 'sentence_vocabulary' as t,'public.sentence_vocabulary'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.sentence_vocabulary x
 union all select 'speaking_sessions' as t,'public.speaking_sessions'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.speaking_sessions x
 union all select 'study_sessions' as t,'public.study_sessions'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.study_sessions x
 union all select 'sync_batches' as t,'public.sync_batches'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.sync_batches x
 union all select 'user_grammar_progress' as t,'public.user_grammar_progress'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.user_grammar_progress x
 union all select 'user_languages' as t,'public.user_languages'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.user_languages x
 union all select 'user_progress' as t,'public.user_progress'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.user_progress x
 union all select 'users' as t,'public.users'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.users x
 union all select 'vocabulary' as t,'public.vocabulary'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.vocabulary x
 union all select 'vocabulary_collocations' as t,'public.vocabulary_collocations'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.vocabulary_collocations x
 union all select 'vocabulary_examples' as t,'public.vocabulary_examples'::regclass::oid as oid,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(x) order by (to_jsonb(x))::text),'[]'::jsonb)::text) as content_md5 from public.vocabulary_examples x
), problems(kind,detail) as (
 select 'missing_table',t.t from tables t where t.oid is null
 union all select 'rls_disabled',t.t from tables t where t.oid is not null and not t.relrowsecurity
 union all select 'unexpected_table',c.relname::text from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p') and not exists(select 1 from expected e where e.t=c.relname)
 union all select 'browser_table_privilege',t.t||':'||r.role_name||':'||p.privilege from tables t cross join (values('anon'),('authenticated')) r(role_name) cross join (values('SELECT'),('INSERT'),('UPDATE'),('DELETE'),('TRUNCATE'),('REFERENCES'),('TRIGGER')) p(privilege) where t.oid is not null and has_table_privilege(r.role_name,t.oid,p.privilege)
 union all select 'private_function_execute',r.role_name||':'||s from (values('anon'),('authenticated')) r(role_name) cross join unnest(array['private.project_state(uuid,jsonb)','private.project_state_v6(uuid,jsonb)','private.project_learning_state(uuid,jsonb)']) s where to_regprocedure(s) is not null and has_function_privilege(r.role_name,to_regprocedure(s),'EXECUTE')
 union all select 'invalid_projection_security','private.project_state(uuid,jsonb)' where not exists(select 1 from pg_catalog.pg_proc p where p.oid=to_regprocedure('private.project_state(uuid,jsonb)') and p.prosecdef and pg_get_userbyid(p.proowner)='postgres' and exists(select 1 from unnest(p.proconfig) x where split_part(x,'=',1)='search_path' and trim(split_part(x,'=',2),E' \'"')=''))
 union all select 'invalid_column',c.table_name||'.'||c.column_name from (values('personal_audio_files','source_updated_at','timestamp with time zone'::regtype),('listening_progress','media_id','text'::regtype)) c(table_name,column_name,type_oid) where not exists(select 1 from pg_catalog.pg_attribute a where a.attrelid=to_regclass('public.'||c.table_name) and a.attname=c.column_name and a.atttypid=c.type_oid and not a.attnotnull and not a.atthasdef and not a.attisdropped)
)
select jsonb_build_object(
 'migration_versions',(select jsonb_agg(m.version order by m.version) from supabase_migrations.schema_migrations m),
 'migration_007_recorded',exists(select 1 from supabase_migrations.schema_migrations m where m.version='007' and m.name='audio_position_identity'),
 'expected_tables',43,'found_tables',(select count(*) from tables t where t.oid is not null),
 'problems',coalesce((select jsonb_agg(jsonb_build_object('check',p.kind,'detail',p.detail) order by p.kind,p.detail) from problems p),'[]'::jsonb),
 'existing_tables_and_data_preserved',coalesce((select jsonb_object_agg(s.t,jsonb_build_object('oid',s.oid,'rows',s.rows,'content_md5',s.content_md5)) from stored_rows s)=(select l.before_rows from ledger l),false),
 'prior_functions_preserved',coalesce(md5((select jsonb_agg(to_jsonb(p)||jsonb_build_object('proname',case when p.oid=to_regprocedure('private.project_state_v6(uuid,jsonb)') then 'project_state' else p.proname end) order by p.oid) from pg_catalog.pg_proc p where p.oid in (select to_regprocedure(s) from unnest(array['public.create_user_profile()','public.configure_private_owner(text)','public.is_private_owner()','public.consume_ai_request(uuid)','private.guard_owner_signup()','private.touch_updated_at()','public.record_review(uuid,uuid,text,timestamptz,integer)','public.sync_personal_state(bigint,text,jsonb)','public.personal_progress(text)','private.resolve_id(uuid,text,text)','private.validate_review_target()','private.create_review_item()','private.create_grammar_review()','private.project_learning_state(uuid,jsonb)','public.claim_ai_request(uuid)','private.validate_personal_snapshot()','private.project_state_v6(uuid,jsonb)','public.due_review_counts(text)','public.export_personal_archive()']) s))::text)=(select l.hashes->>'functions' from ledger l),false),
 'prior_policies_unchanged',coalesce(md5((select jsonb_agg(to_jsonb(p) order by p.schemaname,p.tablename,p.policyname) from pg_catalog.pg_policies p where p.schemaname='public' or (p.schemaname='storage' and p.tablename='objects'))::text)=(select l.hashes->>'policies' from ledger l),false),
 'prior_app_triggers_unchanged',coalesce(md5((select jsonb_agg(to_jsonb(g) order by g.oid) from pg_catalog.pg_trigger g join pg_catalog.pg_class c on c.oid=g.tgrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where not g.tgisinternal and (n.nspname='public' or g.tgrelid='auth.users'::regclass))::text)=(select l.hashes->>'triggers' from ledger l),false),
 'prior_constraints_unchanged',coalesce(md5((select jsonb_agg(to_jsonb(c) order by c.oid) from pg_catalog.pg_constraint c join pg_catalog.pg_class r on r.oid=c.conrelid join pg_catalog.pg_namespace n on n.oid=r.relnamespace where n.nspname='public')::text)=(select l.hashes->>'constraints' from ledger l),false),
 'prior_columns_unchanged',coalesce(md5((select jsonb_agg(to_jsonb(a) order by a.attrelid,a.attnum) from pg_catalog.pg_attribute a join pg_catalog.pg_class c on c.oid=a.attrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and a.attnum>0 and not a.attisdropped and not ((c.relname='personal_audio_files' and a.attname='source_updated_at') or (c.relname='listening_progress' and a.attname='media_id')))::text)=(select l.hashes->>'columns' from ledger l),false),
 'new_columns_unchanged',coalesce(md5((select jsonb_agg(to_jsonb(a) order by a.attrelid,a.attnum) from pg_catalog.pg_attribute a where (a.attrelid='public.personal_audio_files'::regclass and a.attname='source_updated_at') or (a.attrelid='public.listening_progress'::regclass and a.attname='media_id'))::text)=(select l.hashes->>'new_columns' from ledger l),false),
 'installed_function_unchanged',coalesce(md5((select to_jsonb(p) from pg_catalog.pg_proc p where p.oid=to_regprocedure('private.project_state(uuid,jsonb)'))::text)=(select l.hashes->>'installed_function' from ledger l),false),
 'new_columns_unfilled',not exists(select 1 from public.personal_audio_files a where a.source_updated_at is not null) and not exists(select 1 from public.listening_progress p where p.media_id is not null),
 'owner_configured',(select count(*)=1 and bool_and(o.email='yzh72339@gmail.com') from private.app_owner o),
 'owner_table_rls',(select c.relrowsecurity from pg_catalog.pg_class c where c.oid='private.app_owner'::regclass),
 'browser_private_schema_access',has_schema_privilege('anon','private','USAGE') or has_schema_privilege('authenticated','private','USAGE'),
 'browser_owner_table_access',exists(select 1 from (values('anon'),('authenticated')) r(role_name) cross join (values('SELECT'),('INSERT'),('UPDATE'),('DELETE'),('TRUNCATE'),('REFERENCES'),('TRIGGER')) p(privilege) where has_table_privilege(r.role_name,'private.app_owner',p.privilege)),
 'private_buckets',(select count(*) from storage.buckets b where b.id in ('personal-audio','personal-backups','personal-content') and not b.public),
 'auth_profile_trigger_present',exists(select 1 from pg_catalog.pg_trigger g where g.tgrelid='auth.users'::regclass and g.tgname='on_auth_user_created' and g.tgfoid=to_regprocedure('public.create_user_profile()') and g.tgtype=5 and g.tgenabled='O'),
 'signup_guard_present',exists(select 1 from pg_catalog.pg_trigger g where g.tgrelid='auth.users'::regclass and g.tgname='allow_private_owner_only' and g.tgfoid=to_regprocedure('private.guard_owner_signup()') and g.tgtype=7 and g.tgenabled='O'),
 'storage_rls',(select c.relrowsecurity from pg_catalog.pg_class c where c.oid='storage.objects'::regclass),
 'ledger_rls',(select c.relrowsecurity from pg_catalog.pg_class c where c.oid='supabase_migrations.schema_migrations'::regclass),
 'browser_ledger_schema_access',has_schema_privilege('anon','supabase_migrations','USAGE') or has_schema_privilege('authenticated','supabase_migrations','USAGE'),
 'rls_helper_unchanged',coalesce((select md5(to_jsonb(p)::text) from pg_catalog.pg_proc p where p.oid=to_regprocedure('public.rls_auto_enable()'))=(select substring(m.statements[2] from 'helper_catalog_md5=([a-f0-9]{32})') from supabase_migrations.schema_migrations m where m.version='007'),false),
 'ensure_rls_unchanged',coalesce((select md5(to_jsonb(e)::text) from pg_catalog.pg_event_trigger e where e.evtname='ensure_rls')=(select substring(m.statements[2] from 'ensure_rls_catalog_md5=([a-f0-9]{32})') from supabase_migrations.schema_migrations m where m.version='007'),false)
) as migration_007_verification;
