-- Only migration 009. Run the whole file as postgres after 008 verification passes.
-- Minimum table grants + restrictive owner fences. No accounts or learning data created.
begin;
set local lock_timeout='5s';
set local statement_timeout='120s';
do $deploy_009$
declare
 v_sql text:=$migration_009$
-- Restrict privileges independently of Supabase's project default grants.
-- RLS does not protect TRUNCATE, so the browser must never receive it.
alter table private.app_owner enable row level security;
revoke all on private.app_owner from public,anon,authenticated;

do $$declare t text; owned_column text;begin
 foreach t in array array[
  'users','profiles','user_languages','vocabulary','vocabulary_examples','vocabulary_collocations',
  'grammar','grammar_relations','grammar_examples','user_grammar_progress','articles','reading_progress',
  'saved_sentences','sentence_vocabulary','sentence_grammar','review_items','review_logs',
  'listening_episodes','listening_progress','speaking_sessions','mistakes','ai_conversations','ai_messages',
  'daily_plans','study_sessions','personal_notes','backups','downloads','sync_batches','client_id_map',
  'user_progress','ai_requests','ai_usage','personal_audio_files','languages','courses','lessons',
  'legacy_profiles','legacy_vocabulary','legacy_grammar','legacy_reviews','legacy_study_sessions','legacy_ai_conversations'
 ] loop
  execute format('alter table public.%I enable row level security',t);
  execute format('revoke all on public.%I from public,anon,authenticated',t);
  if t='ai_usage' then continue;end if;
  if t in ('users','user_progress','review_items','review_logs','sync_batches','client_id_map','ai_requests',
           'languages','courses','lessons','legacy_profiles','legacy_vocabulary','legacy_grammar',
           'legacy_reviews','legacy_study_sessions','legacy_ai_conversations') then
   execute format('grant select on public.%I to authenticated',t);
  else
   execute format('grant select,insert,update,delete on public.%I to authenticated',t);
  end if;
  -- Restrictive policies combine with the existing ownership/parent policies
  -- using AND. Another permissive policy cannot reopen this private app.
  select a.attname into owned_column from pg_catalog.pg_attribute a
   where a.attrelid=format('public.%I',t)::regclass and a.attname='user_id' and not a.attisdropped;
  if t in ('profiles','users') then owned_column:='id';end if;
  if owned_column is not null then
   execute format('create policy private_owner_fence on public.%I as restrictive for all to authenticated using(public.is_private_owner() and %I=auth.uid()) with check(public.is_private_owner() and %I=auth.uid())',t,owned_column,owned_column);
  else
   execute format('create policy private_owner_fence on public.%I as restrictive for all to authenticated using(public.is_private_owner()) with check(public.is_private_owner())',t);
  end if;
 end loop;
end;$$;

-- Preserve existing objects while making matching buckets private too.
update storage.buckets set public=false
 where id in ('personal-audio','personal-backups','personal-content') and public is distinct from false;
-- Only these three buckets are fenced; unrelated project buckets are untouched.
create policy managed_storage_owner_fence on storage.objects as restrictive for all to authenticated
 using(bucket_id not in ('personal-audio','personal-backups','personal-content') or
  (public.is_private_owner() and (storage.foldername(name))[1]=auth.uid()::text))
 with check(bucket_id not in ('personal-audio','personal-backups','personal-content') or
  (public.is_private_owner() and (storage.foldername(name))[1]=auth.uid()::text));
create policy managed_storage_anon_fence on storage.objects as restrictive for all to anon
 using(bucket_id not in ('personal-audio','personal-backups','personal-content'))
 with check(bucket_id not in ('personal-audio','personal-backups','personal-content'));
revoke all on function public.create_user_profile() from public,anon,authenticated;
$migration_009$;
 v_tables text[]:=array['ai_conversations','ai_messages','ai_requests','ai_usage','articles','backups','client_id_map','courses','daily_plans','downloads','grammar','grammar_examples','grammar_relations','languages','legacy_ai_conversations','legacy_grammar','legacy_profiles','legacy_reviews','legacy_study_sessions','legacy_vocabulary','lessons','listening_episodes','listening_progress','mistakes','personal_audio_files','personal_notes','profiles','reading_progress','review_items','review_logs','saved_sentences','sentence_grammar','sentence_vocabulary','speaking_sessions','study_sessions','sync_batches','user_grammar_progress','user_languages','user_progress','users','vocabulary','vocabulary_collocations','vocabulary_examples'];
 v_table text;v_count bigint;v_digest text;v_rows jsonb:='{}';v_before jsonb;
 v_helper jsonb;v_event jsonb;v_catalog jsonb;
begin
 perform pg_advisory_xact_lock(hashtext('kotoba-dashboard-migrations'));
 if current_user<>'postgres' then raise exception 'Use postgres in SQL Editor';end if;
 if (select array_agg(m.version order by m.version) from supabase_migrations.schema_migrations m) is distinct from array['001','002','003','004','005','006','007','008']
  or not exists(select 1 from supabase_migrations.schema_migrations m where m.version='008' and m.name='phase_one_private_account') then raise exception 'Expected only verified migrations 001 through 008';end if;
 if (select array_agg(c.relname::text order by c.relname::text) from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p')) is distinct from v_tables then raise exception 'Public table inventory differs from verified 008';end if;
 if exists(select 1 from pg_catalog.pg_policies p where (p.schemaname='public' and p.policyname='private_owner_fence') or (p.schemaname='storage' and p.tablename='objects' and p.policyname in ('managed_storage_owner_fence','managed_storage_anon_fence'))) then raise exception 'A 009 policy already exists; stop instead of overwriting';end if;
 lock table auth.users,public.ai_conversations,public.ai_messages,public.ai_requests,public.ai_usage,public.articles,public.backups,public.client_id_map,public.courses,public.daily_plans,public.downloads,public.grammar,public.grammar_examples,public.grammar_relations,public.languages,public.legacy_ai_conversations,public.legacy_grammar,public.legacy_profiles,public.legacy_reviews,public.legacy_study_sessions,public.legacy_vocabulary,public.lessons,public.listening_episodes,public.listening_progress,public.mistakes,public.personal_audio_files,public.personal_notes,public.profiles,public.reading_progress,public.review_items,public.review_logs,public.saved_sentences,public.sentence_grammar,public.sentence_vocabulary,public.speaking_sessions,public.study_sessions,public.sync_batches,public.user_grammar_progress,public.user_languages,public.user_progress,public.users,public.vocabulary,public.vocabulary_collocations,public.vocabulary_examples,private.app_owner,storage.buckets in share row exclusive mode;
 if (select count(*) from private.app_owner)<>1 or not exists(select 1 from private.app_owner o where o.email='yzh72339@gmail.com')
  or md5((select (to_jsonb(o)-'user_id')::text from private.app_owner o)) is distinct from (select m.statements[4]::jsonb->>'owner_base' from supabase_migrations.schema_migrations m where m.version='008') then raise exception 'Private owner checkpoint differs';end if;
 if (select count(*) from auth.users u where lower(u.email)='yzh72339@gmail.com')>1
  or not exists(select 1 from private.app_owner o where (o.user_id is null and not exists(select 1 from auth.users u where lower(u.email)=o.email)) or exists(select 1 from auth.users u where u.id=o.user_id and lower(u.email)=o.email)) then raise exception 'Owner Auth identity is inconsistent';end if;
 if exists(select 1 from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where ((n.nspname='public' and c.relkind in ('r','p')) or c.oid in ('private.app_owner'::regclass,'storage.objects'::regclass,'supabase_migrations.schema_migrations'::regclass)) and not c.relrowsecurity) then raise exception 'RLS checkpoint changed';end if;
 if exists(select 1 from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace cross join (values('anon'),('authenticated')) r(role_name) cross join (values('SELECT'),('INSERT'),('UPDATE'),('DELETE'),('TRUNCATE'),('REFERENCES'),('TRIGGER'),('MAINTAIN')) p(privilege) where n.nspname='public' and c.relkind in ('r','p') and has_table_privilege(r.role_name,c.oid,p.privilege)) then raise exception 'Browser table privileges changed before 009';end if;
 if exists(select 'private_schema_access' as kind,r.role_name||':'||n.schema_name as detail from (values('anon'),('authenticated')) r(role_name) cross join (values('private'),('supabase_migrations')) n(schema_name) where has_schema_privilege(r.role_name,n.schema_name,'USAGE') or has_schema_privilege(r.role_name,n.schema_name,'CREATE')
 union all select 'browser_public_create',r.role_name from (values('anon'),('authenticated')) r(role_name) where has_schema_privilege(r.role_name,'public','CREATE')
 union all select 'private_table_access',r.role_name||':'||c.oid::regclass::text||':'||p.privilege from pg_catalog.pg_class c cross join (values('anon'),('authenticated')) r(role_name) cross join (values('SELECT'),('INSERT'),('UPDATE'),('DELETE'),('TRUNCATE'),('REFERENCES'),('TRIGGER'),('MAINTAIN')) p(privilege) where c.oid in ('private.app_owner'::regclass,'supabase_migrations.schema_migrations'::regclass) and has_table_privilege(r.role_name,c.oid,p.privilege)
 union all select 'private_function_execute',r.role_name||':'||p.oid::regprocedure::text from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace cross join (values('anon'),('authenticated')) r(role_name) where (n.nspname='private' or p.oid in (to_regprocedure('public.create_user_profile()'),to_regprocedure('public.configure_private_owner(text)'))) and has_function_privilege(r.role_name,p.oid,'EXECUTE')) then raise exception 'Private permissions checkpoint changed';end if;
 if (select count(*) from storage.buckets b where b.id in ('personal-audio','personal-backups','personal-content') and not b.public)<>3 then raise exception 'Managed buckets must stay private';end if;
 select to_jsonb(p) into v_helper from pg_catalog.pg_proc p where p.oid=to_regprocedure('public.rls_auto_enable()');
 select to_jsonb(e) into v_event from pg_catalog.pg_event_trigger e where e.evtname='ensure_rls';
 if v_helper is null or v_event is null
  or md5(v_helper::text) is distinct from (select substring(m.statements[2] from 'helper_catalog_md5=([a-f0-9]{32})') from supabase_migrations.schema_migrations m where m.version='008')
  or md5(v_event::text) is distinct from (select substring(m.statements[2] from 'ensure_rls_catalog_md5=([a-f0-9]{32})') from supabase_migrations.schema_migrations m where m.version='008') then raise exception 'RLS helper differs from verified 008';end if;
 if md5((select jsonb_agg(to_jsonb(p)||jsonb_build_object('proname',case when p.oid=to_regprocedure('private.project_state_v7(uuid,jsonb)') then 'project_state' else p.proname end) order by p.oid) from pg_catalog.pg_proc p where p.oid in (select to_regprocedure(s) from unnest(array['public.consume_ai_request(uuid)','private.touch_updated_at()','public.record_review(uuid,uuid,text,timestamptz,integer)','public.sync_personal_state(bigint,text,jsonb)','public.personal_progress(text)','private.resolve_id(uuid,text,text)','private.validate_review_target()','private.create_review_item()','private.create_grammar_review()','private.project_learning_state(uuid,jsonb)','public.claim_ai_request(uuid)','private.validate_personal_snapshot()','private.project_state_v6(uuid,jsonb)','public.due_review_counts(text)','public.export_personal_archive()','private.project_state_v7(uuid,jsonb)']) s))::text) is distinct from (select m.statements[4]::jsonb->>'functions' from supabase_migrations.schema_migrations m where m.version='008')
  or md5((select jsonb_agg(to_jsonb(p) order by p.schemaname,p.tablename,p.policyname) from pg_catalog.pg_policies p where p.schemaname='public' or (p.schemaname='storage' and p.tablename='objects'))::text) is distinct from (select m.statements[4]::jsonb->>'policies' from supabase_migrations.schema_migrations m where m.version='008')
  or md5((select jsonb_agg(to_jsonb(g) order by g.oid) from pg_catalog.pg_trigger g join pg_catalog.pg_class c on c.oid=g.tgrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where not g.tgisinternal and (n.nspname='public' or g.tgrelid='auth.users'::regclass))::text) is distinct from (select m.statements[4]::jsonb->>'triggers' from supabase_migrations.schema_migrations m where m.version='008')
  or md5((select jsonb_agg(to_jsonb(c) order by c.oid) from pg_catalog.pg_constraint c join pg_catalog.pg_class r on r.oid=c.conrelid join pg_catalog.pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and not ((r.relname='user_languages' and c.conname in ('valid_current_language_level','valid_target_language_level')) or (r.relname='profiles' and c.conname in ('profile_name_length','profile_native_language_length','profile_timezone_length'))))::text) is distinct from (select m.statements[4]::jsonb->>'constraints' from supabase_migrations.schema_migrations m where m.version='008')
  or md5((select jsonb_agg(to_jsonb(a) order by a.attrelid,a.attnum) from pg_catalog.pg_attribute a join pg_catalog.pg_class c on c.oid=a.attrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and a.attnum>0 and not a.attisdropped)::text) is distinct from (select m.statements[4]::jsonb->>'columns' from supabase_migrations.schema_migrations m where m.version='008')
  or md5((select jsonb_agg(to_jsonb(p) order by p.oid) from pg_catalog.pg_proc p where p.oid in (select to_regprocedure(s) from unnest(array['public.is_private_owner()','public.configure_private_owner(text)','private.guard_owner_signup()','public.create_user_profile()','private.ensure_private_profile(uuid)','public.get_private_account()','private.project_state(uuid,jsonb)']) s))::text) is distinct from (select m.statements[4]::jsonb->>'installed_functions' from supabase_migrations.schema_migrations m where m.version='008')
  or md5((select jsonb_agg(to_jsonb(c) order by c.oid) from pg_catalog.pg_constraint c where (c.conrelid='public.user_languages'::regclass and c.conname in ('valid_current_language_level','valid_target_language_level')) or (c.conrelid='public.profiles'::regclass and c.conname in ('profile_name_length','profile_native_language_length','profile_timezone_length')) or (c.conrelid='private.app_owner'::regclass and c.conname in ('app_owner_user_id_key','app_owner_user_id_fkey')))::text) is distinct from (select m.statements[4]::jsonb->>'new_constraints' from supabase_migrations.schema_migrations m where m.version='008')
  or md5((select to_jsonb(a) from pg_catalog.pg_attribute a where a.attrelid='private.app_owner'::regclass and a.attname='user_id' and not a.attisdropped)::text) is distinct from (select m.statements[4]::jsonb->>'owner_column' from supabase_migrations.schema_migrations m where m.version='008') then raise exception 'Objects differ from verified 008';end if;
 v_catalog:=jsonb_build_object('functions',md5((select jsonb_agg(to_jsonb(p) order by p.oid) from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private'))::text),'policies',md5((select jsonb_agg(to_jsonb(p) order by p.schemaname,p.tablename,p.policyname) from pg_catalog.pg_policies p where (p.schemaname='public' or (p.schemaname='storage' and p.tablename='objects')) and not ((p.schemaname='public' and p.tablename=any(array['ai_conversations','ai_messages','ai_requests','articles','backups','client_id_map','courses','daily_plans','downloads','grammar','grammar_examples','grammar_relations','languages','legacy_ai_conversations','legacy_grammar','legacy_profiles','legacy_reviews','legacy_study_sessions','legacy_vocabulary','lessons','listening_episodes','listening_progress','mistakes','personal_audio_files','personal_notes','profiles','reading_progress','review_items','review_logs','saved_sentences','sentence_grammar','sentence_vocabulary','speaking_sessions','study_sessions','sync_batches','user_grammar_progress','user_languages','user_progress','users','vocabulary','vocabulary_collocations','vocabulary_examples']) and p.policyname='private_owner_fence') or (p.schemaname='storage' and p.tablename='objects' and p.policyname in ('managed_storage_owner_fence','managed_storage_anon_fence'))))::text),'triggers',md5((select jsonb_agg(to_jsonb(g) order by g.oid) from pg_catalog.pg_trigger g join pg_catalog.pg_class c on c.oid=g.tgrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where not g.tgisinternal and (n.nspname in ('public','private') or g.tgrelid='auth.users'::regclass))::text),'constraints',md5((select jsonb_agg(to_jsonb(c) order by c.oid) from pg_catalog.pg_constraint c join pg_catalog.pg_class r on r.oid=c.conrelid join pg_catalog.pg_namespace n on n.oid=r.relnamespace where n.nspname in ('public','private'))::text),'columns',md5((select jsonb_agg(to_jsonb(a) order by a.attrelid,a.attnum) from pg_catalog.pg_attribute a join pg_catalog.pg_class c on c.oid=a.attrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and c.relkind='r' and a.attnum>0 and not a.attisdropped)::text),'owner',md5((select to_jsonb(o) from private.app_owner o)::text),'buckets',md5((select jsonb_agg(to_jsonb(b) order by b.id) from storage.buckets b)::text));
 foreach v_table in array v_tables loop
  execute format('select count(*),md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),''[]''::jsonb)::text) from public.%I x',v_table) into v_count,v_digest;
  v_rows:=v_rows||jsonb_build_object(v_table,jsonb_build_object('oid',to_regclass(format('public.%I',v_table))::oid,'rows',v_count,'content_md5',v_digest));
 end loop;
 v_before:=v_rows;

 execute v_sql;

 v_rows:='{}';
 foreach v_table in array v_tables loop
  execute format('select count(*),md5(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text),''[]''::jsonb)::text) from public.%I x',v_table) into v_count,v_digest;
  v_rows:=v_rows||jsonb_build_object(v_table,jsonb_build_object('oid',to_regclass(format('public.%I',v_table))::oid,'rows',v_count,'content_md5',v_digest));
 end loop;
 if v_before is distinct from v_rows then raise exception 'Existing tables or learning records changed; rollback';end if;
 if v_catalog is distinct from jsonb_build_object('functions',md5((select jsonb_agg(to_jsonb(p) order by p.oid) from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private'))::text),'policies',md5((select jsonb_agg(to_jsonb(p) order by p.schemaname,p.tablename,p.policyname) from pg_catalog.pg_policies p where (p.schemaname='public' or (p.schemaname='storage' and p.tablename='objects')) and not ((p.schemaname='public' and p.tablename=any(array['ai_conversations','ai_messages','ai_requests','articles','backups','client_id_map','courses','daily_plans','downloads','grammar','grammar_examples','grammar_relations','languages','legacy_ai_conversations','legacy_grammar','legacy_profiles','legacy_reviews','legacy_study_sessions','legacy_vocabulary','lessons','listening_episodes','listening_progress','mistakes','personal_audio_files','personal_notes','profiles','reading_progress','review_items','review_logs','saved_sentences','sentence_grammar','sentence_vocabulary','speaking_sessions','study_sessions','sync_batches','user_grammar_progress','user_languages','user_progress','users','vocabulary','vocabulary_collocations','vocabulary_examples']) and p.policyname='private_owner_fence') or (p.schemaname='storage' and p.tablename='objects' and p.policyname in ('managed_storage_owner_fence','managed_storage_anon_fence'))))::text),'triggers',md5((select jsonb_agg(to_jsonb(g) order by g.oid) from pg_catalog.pg_trigger g join pg_catalog.pg_class c on c.oid=g.tgrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where not g.tgisinternal and (n.nspname in ('public','private') or g.tgrelid='auth.users'::regclass))::text),'constraints',md5((select jsonb_agg(to_jsonb(c) order by c.oid) from pg_catalog.pg_constraint c join pg_catalog.pg_class r on r.oid=c.conrelid join pg_catalog.pg_namespace n on n.oid=r.relnamespace where n.nspname in ('public','private'))::text),'columns',md5((select jsonb_agg(to_jsonb(a) order by a.attrelid,a.attnum) from pg_catalog.pg_attribute a join pg_catalog.pg_class c on c.oid=a.attrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and c.relkind='r' and a.attnum>0 and not a.attisdropped)::text),'owner',md5((select to_jsonb(o) from private.app_owner o)::text),'buckets',md5((select jsonb_agg(to_jsonb(b) order by b.id) from storage.buckets b)::text)) then raise exception 'Prior functions, policies, schema, owner or buckets changed; rollback';end if;
 if v_helper is distinct from (select to_jsonb(p) from pg_catalog.pg_proc p where p.oid=to_regprocedure('public.rls_auto_enable()')) or v_event is distinct from (select to_jsonb(e) from pg_catalog.pg_event_trigger e where e.evtname='ensure_rls') then raise exception 'RLS helper changed; rollback';end if;
 if exists(with expected(t) as (select unnest(array['ai_conversations','ai_messages','ai_requests','ai_usage','articles','backups','client_id_map','courses','daily_plans','downloads','grammar','grammar_examples','grammar_relations','languages','legacy_ai_conversations','legacy_grammar','legacy_profiles','legacy_reviews','legacy_study_sessions','legacy_vocabulary','lessons','listening_episodes','listening_progress','mistakes','personal_audio_files','personal_notes','profiles','reading_progress','review_items','review_logs','saved_sentences','sentence_grammar','sentence_vocabulary','speaking_sessions','study_sessions','sync_batches','user_grammar_progress','user_languages','user_progress','users','vocabulary','vocabulary_collocations','vocabulary_examples'])), permissions as (
 select e.t,r.role_name,p.privilege,
  (r.role_name='authenticated' and e.t<>'ai_usage' and (p.privilege='SELECT' or (not e.t=any(array['users','user_progress','review_items','review_logs','sync_batches','client_id_map','ai_requests','languages','courses','lessons','legacy_profiles','legacy_vocabulary','legacy_grammar','legacy_reviews','legacy_study_sessions','legacy_ai_conversations']) and p.privilege in ('INSERT','UPDATE','DELETE')))) as allowed
 from expected e cross join (values('anon'),('authenticated')) r(role_name)
 cross join (values('SELECT'),('INSERT'),('UPDATE'),('DELETE'),('TRUNCATE'),('REFERENCES'),('TRIGGER'),('MAINTAIN')) p(privilege)
) select 'table_permission' as kind,p.t||':'||p.role_name||':'||p.privilege as detail from permissions p where has_table_privilege(p.role_name,to_regclass('public.'||p.t),p.privilege) is distinct from p.allowed
 union all select 'column_permission',p.t||'.'||a.attname||':'||p.role_name||':'||p.privilege from permissions p join pg_catalog.pg_attribute a on a.attrelid=to_regclass('public.'||p.t) and a.attnum>0 and not a.attisdropped where case when p.privilege in ('SELECT','INSERT','UPDATE','REFERENCES') then has_column_privilege(p.role_name,a.attrelid,a.attnum,p.privilege) is distinct from p.allowed else false end
 union all select 'private_schema_access' as kind,r.role_name||':'||n.schema_name as detail from (values('anon'),('authenticated')) r(role_name) cross join (values('private'),('supabase_migrations')) n(schema_name) where has_schema_privilege(r.role_name,n.schema_name,'USAGE') or has_schema_privilege(r.role_name,n.schema_name,'CREATE')
 union all select 'browser_public_create',r.role_name from (values('anon'),('authenticated')) r(role_name) where has_schema_privilege(r.role_name,'public','CREATE')
 union all select 'private_table_access',r.role_name||':'||c.oid::regclass::text||':'||p.privilege from pg_catalog.pg_class c cross join (values('anon'),('authenticated')) r(role_name) cross join (values('SELECT'),('INSERT'),('UPDATE'),('DELETE'),('TRUNCATE'),('REFERENCES'),('TRIGGER'),('MAINTAIN')) p(privilege) where c.oid in ('private.app_owner'::regclass,'supabase_migrations.schema_migrations'::regclass) and has_table_privilege(r.role_name,c.oid,p.privilege)
 union all select 'private_function_execute',r.role_name||':'||p.oid::regprocedure::text from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace cross join (values('anon'),('authenticated')) r(role_name) where (n.nspname='private' or p.oid in (to_regprocedure('public.create_user_profile()'),to_regprocedure('public.configure_private_owner(text)'))) and has_function_privilege(r.role_name,p.oid,'EXECUTE')
 union all select 'invalid_table_fence' as kind,e.t as detail from expected e left join pg_catalog.pg_policies p on p.schemaname='public' and p.tablename=e.t and p.policyname='private_owner_fence' where e.t<>'ai_usage' and (p.policyname is null or p.permissive<>'RESTRICTIVE' or p.cmd<>'ALL' or p.roles is distinct from array['authenticated']::name[] or p.qual is null or p.with_check is null or p.qual not like '%is_private_owner()%' or p.with_check not like '%is_private_owner()%')
 union all select 'missing_parent_policy',c.t from (values('vocabulary_examples','parent_owned'),('vocabulary_collocations','parent_owned'),('sentence_vocabulary','both_owned'),('sentence_grammar','sentence_owned')) c(t,n) where not exists(select 1 from pg_catalog.pg_policies p where p.schemaname='public' and p.tablename=c.t and p.policyname=c.n and p.qual like '%auth.uid()%' and p.with_check like '%auth.uid()%')
 union all select 'invalid_storage_fence',e.n from (values('managed_storage_owner_fence','authenticated'),('managed_storage_anon_fence','anon')) e(n,r) left join pg_catalog.pg_policies p on p.schemaname='storage' and p.tablename='objects' and p.policyname=e.n where p.policyname is null or p.permissive<>'RESTRICTIVE' or p.cmd<>'ALL' or p.roles is distinct from array[e.r]::name[] or p.qual is null or p.with_check is null
 union all select 'unconditional_policy',p.tablename||':'||p.policyname from pg_catalog.pg_policies p where p.schemaname='public' and (trim(p.qual,' ()')='true' or trim(p.with_check,' ()')='true')) then raise exception 'Final permissions or restrictive policies are incorrect; rollback';end if;
 insert into supabase_migrations.schema_migrations(version,name,statements) values('009','private_permissions_and_storage',array[
  v_sql,format(E'-- helper_catalog_md5=%s; ensure_rls_catalog_md5=%s\n',md5(v_helper::text),md5(v_event::text)),v_before::text,
  (v_catalog||jsonb_build_object('installed_policies',md5((select jsonb_agg(to_jsonb(p) order by p.schemaname,p.tablename,p.policyname) from pg_catalog.pg_policies p where ((p.schemaname='public' and p.tablename=any(array['ai_conversations','ai_messages','ai_requests','articles','backups','client_id_map','courses','daily_plans','downloads','grammar','grammar_examples','grammar_relations','languages','legacy_ai_conversations','legacy_grammar','legacy_profiles','legacy_reviews','legacy_study_sessions','legacy_vocabulary','lessons','listening_episodes','listening_progress','mistakes','personal_audio_files','personal_notes','profiles','reading_progress','review_items','review_logs','saved_sentences','sentence_grammar','sentence_vocabulary','speaking_sessions','study_sessions','sync_batches','user_grammar_progress','user_languages','user_progress','users','vocabulary','vocabulary_collocations','vocabulary_examples']) and p.policyname='private_owner_fence') or (p.schemaname='storage' and p.tablename='objects' and p.policyname in ('managed_storage_owner_fence','managed_storage_anon_fence'))))::text)))::text
 ]);
end;
$deploy_009$;
commit;
select version,name from supabase_migrations.schema_migrations order by version;
