'use client';
import {useState,useEffect} from 'react';
import {motion,useReducedMotion} from 'framer-motion';
import {Sun,BookOpen,Layers,Type,Headphones,Mic,Repeat2,ChartNoAxesCombined,Sparkles,Settings as SettingsIcon,Search,PanelLeftClose,PanelLeftOpen,ArrowUpRight,ArrowRight,Check,Moon,Home,User,MoreHorizontal,ArrowLeft,Plus,BookMarked,NotebookPen} from 'lucide-react';
import {StudyProvider,useStudy,type Page} from '@/components/study-context';
import {Today,Learn} from '@/components/today';
import {Vocabulary,ReviewPage} from '@/components/vocabulary';
import {Grammar,Reading} from '@/components/reading';
import {Listening} from '@/components/listening';
import {Speaking,AITutor} from '@/components/ai';
import {Progress} from '@/components/progress';
import {Settings} from '@/components/settings';
import {Onboarding} from '@/components/onboarding';
import {Dialog} from '@/components/ui/dialog';
import {SessionHeader,SessionFooter,SessionSidebar,SessionComplete} from '@/components/session-shell';
import {AuthGate} from '@/components/auth-gate';
import {SentenceLibrary,MistakeNotebook,QuickCapture,SelectionActions} from '@/components/personal-tools';
import {PWAProvider,PWAControls} from '@/components/pwa';
import {reviewContent} from '@/lib/review-content';
import {coursePack} from '@/lib/course-library';
const navigation=[{name:'Today',icon:Sun},{name:'Learn',icon:BookOpen},{name:'Vocabulary',icon:Layers},{name:'Grammar',icon:Type},{name:'Reading',icon:BookOpen},{name:'Listening',icon:Headphones},{name:'Speaking',icon:Mic},{name:'Review',icon:Repeat2}] as const;
const secondary=[{name:'My Sentences',icon:BookMarked},{name:'Mistake Notebook',icon:NotebookPen},{name:'Progress',icon:ChartNoAxesCombined},{name:'AI Tutor',icon:Sparkles}] as const;
const bottomNavigation=[{name:'Today',icon:Home},{name:'Learn',icon:BookOpen},{name:'Review',icon:Repeat2},{name:'AI Tutor',icon:Sparkles},{name:'Profile',icon:User}] as const;
function Logo({compact=false}:{compact?:boolean}){return <div className="logo"><span className="logo-mark"><svg viewBox="0 0 28 28" fill="none"><path d="M5 5v18M5 14L20 5M5 14l15 9M12 10v8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg></span>{!compact&&<span>kotoba<span className="logo-period">.</span></span>}</div>}
function App(){
 const {state,setState,page,navigate,setFocusWord,dailySession,sessionPaused,focusMode,changeLanguage,addWord}=useStudy();
 const reduceMotion=useReducedMotion();
 const [collapsed,setCollapsed]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState(''),[setup,setSetup]=useState(false),[more,setMore]=useState(false),[searchIndex,setSearchIndex]=useState(0),[capture,setCapture]=useState(false);
 useEffect(()=>{function key(e:KeyboardEvent){if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(s=>!s)}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 useEffect(()=>{const update=()=>{document.documentElement.style.setProperty('--app-height',`${window.visualViewport?.height??window.innerHeight}px`)};update();window.visualViewport?.addEventListener('resize',update);return()=>window.visualViewport?.removeEventListener('resize',update)},[]);
 const resultWords=[...new Map([...coursePack(state.profile.language,state.profile.level).words.map(w=>({...w,language:state.profile.language})),...Object.values(state.dictionary)].map(w=>[w.id,w])).values()].filter(w=>`${w.word}${w.pronunciation}${w.meaning}${w.related??''}`.toLowerCase().includes(query.toLowerCase())).slice(0,6);
 const results=query?[...resultWords.map(w=>({label:w.word,detail:w.meaning,page:'Vocabulary' as Page,id:w.id,lang:w.language})),...coursePack(state.profile.language,state.profile.level).grammars.filter(g=>g.title.includes(query)).map(g=>({label:g.title,detail:g.meaning,page:'Grammar' as Page,lang:state.profile.language})),...navigation.filter(n=>n.name.toLowerCase().includes(query.toLowerCase())).map(n=>({label:n.name,detail:'Go to page',page:n.name as Page,lang:state.profile.language}))]:[...navigation,...secondary].map(n=>({label:n.name,detail:'Go to page',page:n.name as Page,lang:state.profile.language}));
 function nav(p:Page){navigate(p);setMore(false)}
 function selectResult(i:number){const quick=query.match(/^(?:Add word:|添加单词[:：])\s*(.+)$/i);if(quick){addWord(quick[1]);setSearch(false);setQuery('');return;}const r=results[i];if(!r)return;changeLanguage(r.lang);if('id' in r)setFocusWord(r.id as string);nav(r.page);setSearch(false);setQuery('')}
 function openSearch(){setSearch(true);setQuery('');setSearchIndex(0)}
 const immersive=page==='Speaking'||page==='AI Tutor';
 const shellClasses=['app-shell',collapsed?'sidebar-collapsed':'',dailySession&&!sessionPaused?'daily-session-active':'',focusMode?`focus-${focusMode}`:'',immersive?'immersive-mobile':'',dailySession?.done?'daily-session-done':''].join(' ');
 const view=dailySession?.done?<SessionComplete/>:page==='Today'?<Today onSetup={()=>setSetup(true)}/>:page==='Learn'?<Learn/>:page==='Vocabulary'?<Vocabulary/>:page==='Grammar'?<Grammar/>:page==='Reading'?<Reading/>:page==='Listening'?<Listening/>:page==='Speaking'?<Speaking/>:page==='Review'?<ReviewPage/>:page==='My Sentences'?<SentenceLibrary/>:page==='Mistake Notebook'?<MistakeNotebook/>:page==='Progress'?<Progress/>:page==='AI Tutor'?<AITutor/>:<Settings profile={page==='Profile'} onSetup={()=>setSetup(true)}/>;
 return <div className={shellClasses}>
 <aside className="sidebar" aria-label="主导航"><div className="sidebar-top"><button className="brand-button" aria-label="Kotoba 首页" onClick={()=>nav('Today')}><Logo compact={collapsed}/></button><button className="icon-btn sidebar-toggle" aria-label={collapsed?'展开侧栏':'折叠侧栏'} onClick={()=>setCollapsed(c=>!c)}>{collapsed?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>}</button></div><button className="sidebar-search" onClick={openSearch}><Search size={17}/>{!collapsed&&<><span>Search anything</span><kbd>⌘ K</kbd></>}</button><div className="nav-group"><span className="nav-label">YOUR LEARNING SPACE</span>{navigation.map(n=><button key={n.name} title={n.name} className={`nav-item ${page===n.name?'active':''}`} onClick={()=>nav(n.name)}><n.icon size={18} strokeWidth={1.7}/>{!collapsed&&<><span>{n.name}</span>{n.name==='Review'&&<span className="nav-badge">{reviewContent(state.profile.language,state.profile.level).filter(w=>!state.reviews[w.id]||state.reviews[w.id].due<=Date.now()).length}</span>}</>}</button>)}</div><div className="nav-group secondary-nav">{secondary.map(n=><button key={n.name} title={n.name} className={`nav-item ${page===n.name?'active':''}`} onClick={()=>nav(n.name)}><n.icon size={18} strokeWidth={1.7}/>{!collapsed&&<span>{n.name}</span>}{!collapsed&&n.name==='AI Tutor'&&<span className="ai-beta">AI</span>}</button>)}</div><div className="sidebar-bottom">{!collapsed&&<div className="sidebar-quote"><span>Small steps.</span><span>Wider worlds.</span><small>一日一歩。</small></div>}<button title="Settings" className={`nav-item ${page==='Settings'?'active':''}`} onClick={()=>nav('Settings')}><SettingsIcon size={18}/>{!collapsed&&<span>Settings</span>}</button><button aria-label="个人资料" className="profile-button" onClick={()=>nav('Profile')}><span className="avatar">{state.profile.name.charAt(0)}</span>{!collapsed&&<div><strong>{state.profile.name}</strong><small>{'Private account'}</small></div>}</button></div></aside>
 <div className="main-shell"><header className="topbar"><div className="breadcrumb"><span>Your workspace</span><span className="breadcrumb-slash">/</span><strong>{page}</strong></div><div className="mobile-page-title">{immersive?<button className="icon-btn" aria-label="返回" onClick={()=>nav('Today')}><ArrowLeft size={21}/></button>:null}<strong>{page==='AI Tutor'?'AI Tutor':page==='Speaking'?'Café in Tokyo':page}</strong></div><div className="topbar-right"><button className="desktop-language-control" onClick={()=>setMore(true)}><span className="status-dot"/>{state.profile.language==='ja'?'日本語':'English'}<span className="tag">{state.profile.level}</span></button><button className="icon-btn desktop-theme-control" aria-label="切换深色模式" onClick={()=>setState(s=>({...s,theme:s.theme==='light'?'dark':'light'}))}>{state.theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button><button className="icon-btn" aria-label="全局搜索" onClick={openSearch}><Search size={20}/></button><button className="icon-btn mobile-more-control" aria-label="更多功能" onClick={()=>setMore(true)}><MoreHorizontal size={21}/></button></div></header><SessionHeader/><main className={`main-content page-${page.replace(' ','-').toLowerCase()}`}><div className="session-content-wrap"><motion.div className="page-view" key={page+state.profile.language+state.profile.level+(dailySession?.done?'done':'')} initial={reduceMotion?false:{opacity:0,y:6}} animate={{opacity:1,y:0}} transition={{duration:reduceMotion?0:0.22}}>{view}</motion.div>{dailySession&&!dailySession.done&&!sessionPaused&&<SessionSidebar/>}</div></main><SessionFooter/></div>
 <nav className="bottom-nav" aria-label="移动端导航">{bottomNavigation.map(n=><button key={n.name} aria-current={page===n.name?'page':undefined} className={page===n.name?'active':''} onClick={()=>nav(n.name)}>{page===n.name&&<motion.span className="bottom-nav-indicator" layoutId="bottom-nav-indicator" transition={reduceMotion?{duration:0}:{type:'spring',stiffness:460,damping:38}}/>}<n.icon size={21}/><span>{n.name==='AI Tutor'?'AI':n.name}</span></button>)}</nav>
 <PWAControls/><SelectionActions/><QuickCapture open={capture} onOpenChange={setCapture}/><button className="quick-add-button" aria-label="快速捕捉" onClick={()=>setCapture(true)}><Plus size={19}/><span>Capture</span></button>
 <Onboarding open={setup} onOpenChange={setSetup}/>
 <Dialog open={more} onOpenChange={setMore} title="Your workspace" sheet><div className="more-learning"><span className="eyebrow">LEARNING LANGUAGE</span><div className="more-languages">{(['ja','en'] as const).map(l=><button className={state.profile.language===l?'selected':''} key={l} onClick={()=>{changeLanguage(l);setMore(false)}}>{l==='ja'?'日本語':'English'}{l===state.profile.language&&<Check size={17}/>}</button>)}</div></div><div className="more-menu-grid">{[...navigation.slice(2),...secondary,{name:'Settings' as const,icon:SettingsIcon}].map(n=><button key={n.name} onClick={()=>nav(n.name)}><n.icon size={19}/><span>{n.name}</span><ArrowRight size={16}/></button>)}</div><div className="more-footer"><button onClick={()=>{setMore(false);setSetup(true)}}>Learning preferences <ArrowUpRight size={16}/></button><button onClick={()=>setState(s=>({...s,theme:s.theme==='light'?'dark':'light'}))}>{state.theme==='light'?<Moon size={18}/>:<Sun size={18}/>} {state.theme==='light'?'Dark':'Light'}</button></div></Dialog>
 <Dialog open={search} onOpenChange={setSearch} title="Find a word. Find a way." wide fullScreen><div className="command-search"><Search size={19}/><input autoFocus placeholder="Search words, grammar, lessons…" value={query} onChange={e=>{setQuery(e.target.value);setSearchIndex(0)}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setSearchIndex(i=>Math.min(results.length-1,i+1))}if(e.key==='ArrowUp'){e.preventDefault();setSearchIndex(i=>Math.max(0,i-1))}if(e.key==='Enter'){e.preventDefault();selectResult(searchIndex)}}}/><kbd>ESC</kbd></div><span className="eyebrow command-label">{query?'SEARCH RESULTS':'JUMP TO'}</span><div className="command-results">{query.match(/^(?:Add word:|添加单词[:：])\s*(.+)$/i)&&<button className="active" onClick={()=>selectResult(0)}><Plus size={18}/><span>Add to my dictionary</span><ArrowRight size={16}/></button>}{results.map((r,i)=><button key={r.label+i} className={searchIndex===i?'active':''} onMouseEnter={()=>setSearchIndex(i)} onClick={()=>selectResult(i)}><span className="command-result-icon">{r.page==='Vocabulary'?<Layers size={18}/>:<BookOpen size={18}/>}</span><div><strong>{r.label}</strong><small>{r.detail}</small></div><span>{r.page}</span><ArrowRight size={15}/></button>)}{results.length===0&&<div className="empty-state">没有找到结果。试试「余裕」「わけ」或「take」。</div>}</div><div className="command-footer"><span><kbd>↑</kbd><kbd>↓</kbd> to navigate</span><span><kbd>↵</kbd> to open</span></div></Dialog>
 </div>
}
export default function Page(){return <AuthGate><StudyProvider><PWAProvider><App/></PWAProvider></StudyProvider></AuthGate>}
