'use client';
import {useState,useEffect,useRef} from 'react';
import {ArrowLeft,ArrowRight,Check,Clock,Compass} from 'lucide-react';
import {useStudy} from './study-context';
import {Dialog} from './ui/dialog';
import {Button} from './ui/button';
import {type Profile} from '@/lib/store';
export function Onboarding({open,onOpenChange}:{open:boolean;onOpenChange:(v:boolean)=>void}){const {state,setState,navigate,notify}=useStudy();const [step,setStep]=useState(0),[profile,setProfile]=useState<Profile>(state.profile);const wasOpen=useRef(false);useEffect(()=>{if(open&&!wasOpen.current){setStep(0);setProfile(state.profile)}wasOpen.current=open},[open,state.profile]);const titles=['A new language. A wider world.','Start where you are.','What brings you here?','A little time, every day.'];function finish(){setState(s=>({...s,languageProfiles:{...s.languageProfiles,[profile.language]:{...s.languageProfiles[profile.language],level:profile.level,goal:profile.goal}},profile:{...profile,onboarded:true}}));onOpenChange(false);navigate('Learn');notify('你的专属学习路径已准备好。')}
return <Dialog open={open} onOpenChange={onOpenChange} title="Welcome to Kotoba" wide><div className="onboarding"><div className="onboarding-progress">{[0,1,2,3].map(i=><span className={i<=step?'active':''} key={i}/>)}</div><span className="eyebrow">STEP 0{step+1} OF 04</span><h2>{titles[step]}</h2><p>{['你想用哪一种语言，认识这个世界？','选择你当前的水平。随时可以调整。','告诉我们你的方向，我们一起走。','不需要很多时间，只需要一点坚持。'][step]}</p>{step===0&&<div className="language-options">{([{id:'ja',name:'日本語',sub:'Japanese',symbol:'あ'},{id:'en',name:'English',sub:'英语',symbol:'Aa'}] as const).map(l=><button className={profile.language===l.id?'selected':''} key={l.id} onClick={()=>setProfile(p=>({...p,language:l.id,level:l.id==='ja'?'N3':'B1'}))}><span className="language-symbol">{l.symbol}</span><strong>{l.name}</strong><small>{l.sub}</small>{profile.language===l.id&&<Check size={18}/>}</button>)}</div>}{step===1&&<div className="choice-grid levels">{(profile.language==='ja'?['N5','N4','N3','N2','N1']:['A1','A2','B1','B2','C1','C2']).map((l,i)=><button className={profile.level===l?'selected':''} key={l} onClick={()=>setProfile(p=>({...p,level:l}))}><strong>{l}</strong><small>{['起步','基础','进阶','熟练','高级','精通'][i]}</small></button>)}</div>}{step===2&&<div className="choice-grid">{['日常交流','留学','考试','商务','旅行','兴趣'].map(g=><button className={profile.goal===g?'selected':''} key={g} onClick={()=>setProfile(p=>({...p,goal:g}))}><Compass size={18}/>{g}</button>)}</div>}{step===3&&<div className="choice-grid time-choices">{[15,20,30,45].map(t=><button className={profile.dailyGoal===t?'selected':''} key={t} onClick={()=>setProfile(p=>({...p,dailyGoal:t}))}><Clock size={19}/><strong>{t}<small>min</small></strong><span>{t===10?'轻松起步':t===20?'稳步前进':t===30?'深入一点':'沉浸学习'}</span></button>)}</div>}<div className="onboarding-bottom"><Button variant="ghost" disabled={step===0} onClick={()=>setStep(s=>s-1)}><ArrowLeft size={16}/>Back</Button><Button onClick={()=>step===3?finish():setStep(s=>s+1)}>{step===3?'Create my learning path':'Continue'}<ArrowRight size={16}/></Button></div></div></Dialog>}
