'use client';
import {ArrowLeft,ArrowRight,Check,Clock} from 'lucide-react';
import {useStudy} from './study-context';
import {DAILY_STEPS} from '@/lib/daily-session';
import {Button} from './ui/button';
export function SessionHeader(){const {dailySession,sessionPaused,endSession,state}=useStudy();if(!dailySession||dailySession.done||sessionPaused)return null;return <header className="session-topbar"><button className="icon-btn" aria-label="暂停今日学习并返回 Today" onClick={endSession}><ArrowLeft size={21}/></button><span className="session-current"><strong>{DAILY_STEPS[dailySession.step]}</strong><small>Step {dailySession.step+1} of {DAILY_STEPS.length}</small></span><span><Clock size={14}/>{state.profile.dailyGoal} min goal</span><div className="session-header-progress" role="progressbar" aria-label="今日学习进度" aria-valuenow={dailySession.completed.length} aria-valuemin={0} aria-valuemax={DAILY_STEPS.length}><span style={{width:`${dailySession.completed.length/DAILY_STEPS.length*100}%`}}/></div></header>}
export function SessionSidebar(){const {dailySession,sessionPaused}=useStudy();if(!dailySession||dailySession.done||sessionPaused)return null;return <aside className="session-sidebar"><span className="eyebrow">TODAY’S SESSION</span><h2>A little of everything.</h2>{DAILY_STEPS.map((s,i)=><div className={i===dailySession.step?'active':''} key={s}>{dailySession.completed.includes(s)?<Check size={16}/>:<span className={i===dailySession.step?'session-dot active':'session-dot'}/>}<span>{s}</span></div>)}<p>One step at a time.</p></aside>}
export function SessionFooter(){const {dailySession,sessionPaused,advanceSession}=useStudy();if(!dailySession||dailySession.done||sessionPaused)return null;const ready=dailySession.completed.includes(DAILY_STEPS[dailySession.step]);const next=dailySession.step===3?'Session complete':DAILY_STEPS[dailySession.step+1];return <div className="session-footer"><p role="status">{ready?`已完成 ${DAILY_STEPS[dailySession.step]} · 下一步 ${next}`:dailySession.step===0?'完成当前复习队列后继续。':dailySession.step===1?'完成语法小测验后继续。':dailySession.step===2?'阅读完毕，点击 Mark as read。':'输入或说出一句表达，获取建议后继续。'}</p><Button disabled={!ready} onClick={advanceSession}>{dailySession.step===3?'Finish session':`Continue to ${next}`}<ArrowRight size={17}/></Button></div>}
export function SessionComplete(){const {state,dailySession,endSession}=useStudy();if(!dailySession)return null;const sessions=state.sessions.filter(s=>s.language===dailySession.language&&(s.at??0)>=dailySession.startedAt);const cards=sessions.filter(s=>s.type==='Review').reduce((a,s)=>a+s.count,0);const minutes=Math.round(sessions.reduce((sum,s)=>sum+s.minutes,0)*10)/10;return <div className="session-complete daily-complete"><span className="completion-icon"><Check size={29}/></span><span className="eyebrow">A LITTLE PROGRESS, ALL YOURS</span><h1>Session complete.</h1><p>今天的这一小步，已经留下了痕迹。</p><div className="daily-complete-stats"><div><strong>{minutes}<small>min</small></strong><span>Time well spent</span></div><div><strong>{cards}</strong><span>Cards reviewed</span></div><div><strong>{dailySession.completed.includes('Grammar')?1:0}</strong><span>Grammar learned</span></div><div><strong>{sessions.filter(s=>s.type==='Speaking').length}</strong><span>Speaking practice</span></div></div><Button onClick={endSession}>Done <Check size={17}/></Button></div>}
