'use client';
import {useEffect,useRef} from 'react';
import {ArrowLeft,ArrowRight,Check,Clock} from 'lucide-react';
import {useStudy} from './study-context';
import {sessionSteps} from '@/lib/content-library/daily-course-plan';
import {DAILY_STEPS} from '@/lib/daily-session';
import {Button} from './ui/button';
const stepLabels:Record<string,string>={Review:'到期复习',Grammar:'理解新语法',Reading:'在阅读中运用',Speaking:'开口练习'};
export function SessionHeader(){const {dailySession,sessionPaused,endSession,state}=useStudy();if(!dailySession||dailySession.done||sessionPaused)return null;return <header className="session-topbar"><button className="icon-btn" aria-label="暂停今日学习并返回 Today" onClick={endSession}><ArrowLeft size={21}/></button><span className="session-current"><strong>{stepLabels[DAILY_STEPS[dailySession.step]]}</strong><small>今日学习 · {dailySession.step+1} / {sessionSteps(state).length}</small></span><span className="session-time"><Clock size={14}/>{state.profile.dailyGoal} min 目标</span><div className="session-header-progress" role="progressbar" aria-label="今日学习进度" aria-valuenow={dailySession.completed.length} aria-valuemin={0} aria-valuemax={sessionSteps(state).length}><span style={{transform:`scaleX(${dailySession.completed.length/sessionSteps(state).length})`}}/></div></header>}
export function SessionSidebar(){const {state,dailySession,sessionPaused}=useStudy();if(!dailySession||dailySession.done||sessionPaused)return null;return <aside className="session-sidebar"><span className="eyebrow">TODAY’S SESSION</span><h2>A little of everything.</h2>{sessionSteps(state).map((s,i)=><div className={i===dailySession.step?'active':''} key={s}>{dailySession.completed.includes(s)?<Check size={16}/>:<span className={i===dailySession.step?'session-dot active':'session-dot'}/>}<span>{s}</span></div>)}<p>One step at a time.</p></aside>}
export function SessionFooter(){const {state,dailySession,sessionPaused,advanceSession}=useStudy();const footer=useRef<HTMLDivElement>(null),active=Boolean(dailySession&&!dailySession.done&&!sessionPaused);useEffect(()=>{if(!active||!footer.current)return;const root=document.documentElement,measure=()=>root.style.setProperty('--session-footer-height',`${Math.ceil(footer.current?.getBoundingClientRect().height??0)}px`);measure();const observer=typeof ResizeObserver==='undefined'?null:new ResizeObserver(measure);observer?.observe(footer.current);window.addEventListener('resize',measure);return()=>{observer?.disconnect();window.removeEventListener('resize',measure);root.style.removeProperty('--session-footer-height')}},[active]);if(!dailySession||dailySession.done||sessionPaused)return null;const ready=dailySession.completed.includes(DAILY_STEPS[dailySession.step]);const last=dailySession.step===sessionSteps(state).length-1;const next=last?'Session complete':DAILY_STEPS[dailySession.step+1];return <div ref={footer} className="session-footer"><p role="status">{ready?`已完成 ${stepLabels[DAILY_STEPS[dailySession.step]]} · ${last?'收好今天的进步':'下一步：'+stepLabels[next]}`:dailySession.step===0?'完成当前复习队列后继续。':dailySession.step===1?'完成本课语法练习后继续。':dailySession.step===2?'完成阅读理解后继续；基础阅读请点击 Mark as read。':'输入或说出一句表达，获取建议后继续。'}</p><Button disabled={!ready} onClick={advanceSession}>{last?'查看学习结果':`继续 · ${stepLabels[next]}`}<ArrowRight size={17}/></Button></div>}
export function SessionComplete(){const {state,dailySession,endSession}=useStudy();if(!dailySession)return null;const sessions=state.sessions.filter(s=>s.language===dailySession.language&&(s.at??0)>=dailySession.startedAt);const cards=sessions.filter(s=>s.type==='Review').reduce((a,s)=>a+s.count,0);const minutes=Math.round(sessions.reduce((sum,s)=>sum+s.minutes,0)*10)/10;return <div className="session-complete daily-complete"><span className="completion-icon"><Check size={29}/></span><span className="eyebrow">PROGRESS, MADE PERSONAL</span><h1>今天，又向前一步。</h1><p>从记住一个词，到读懂一个新的世界。</p><div className="daily-complete-stats"><div><strong>{minutes}<small>min</small></strong><span>实际学习分钟</span></div><div><strong>{cards}</strong><span>完成复习</span></div><div><strong>{dailySession.completed.includes('Grammar')?1:0}</strong><span>学会语法</span></div><div><strong>{sessionSteps(state).includes('Speaking')?sessions.filter(s=>s.type==='Speaking').length:dailySession.completed.includes('Reading')?1:0}</strong><span>{sessionSteps(state).includes('Speaking')?'口语练习':'完成阅读'}</span></div></div><Button onClick={endSession}>返回首页 <Check size={17}/></Button></div>}
