'use client';
import {createContext,useContext,useEffect,useState,useRef,useCallback} from 'react';
import {initialState,loadState,migrateState,STORAGE_KEY,today,type AppState} from '@/lib/store';
import {supabase} from '@/lib/supabase';
import {DAILY_STEPS,advanceDailySession,restoreDailySession,shouldPauseDailySession,type DailySession} from '@/lib/daily-session';
import {type Word,type Language} from '@/lib/content';
import {coursePack} from '@/lib/course-library';
import {read,write,entries} from '@/lib/platform/storage';
import {network} from '@/lib/platform/network';
import {persistLearningState} from '@/lib/learning-storage';
import {speakText,stopSpeech} from '@/lib/platform/audio';
import {stampChanges,mergeStates} from '@/lib/sync-state';
import {SyncEngine,type SyncStatus} from '@/lib/sync-engine';
import {captureWord,captureSentence,createMistake,buildDailyPlan} from '@/lib/learning-memory';
import {aiProvider} from '@/lib/ai-provider';
import {dailyPlanRequestId} from '@/lib/daily-plan-request';
import {requestBackgroundSync} from '@/lib/platform/background-sync';
import {subtleFeedback} from '@/lib/platform/haptics';
export type Page='Today'|'Learn'|'Vocabulary'|'Grammar'|'Reading'|'Listening'|'Speaking'|'Review'|'Progress'|'AI Tutor'|'Settings'|'Profile'|'My Sentences'|'Mistake Notebook';
const pages:Page[]=['Today','Learn','Vocabulary','Grammar','Reading','Listening','Speaking','Review','Progress','AI Tutor','Settings','Profile','My Sentences','Mistake Notebook'];
type Context={state:AppState;setState:React.Dispatch<React.SetStateAction<AppState>>;page:Page;navigate:(p:Page)=>void;notify:(s:string)=>void;save:(id:string)=>void;record:(type:string,count?:number)=>void;speak:(text:string,rate?:number,onEnd?:()=>void)=>void;words:Word[];focusWord:string|null;setFocusWord:React.Dispatch<React.SetStateAction<string|null>>;userId:string|null;tutorPrompt:string;setTutorPrompt:React.Dispatch<React.SetStateAction<string>>;ready:boolean;dailySession:DailySession|null;sessionPaused:boolean;startDailySession:()=>void;advanceSession:()=>void;completeDailyStep:(step:string)=>void;endSession:()=>void;focusMode:'reading'|'cards'|null;setFocusMode:React.Dispatch<React.SetStateAction<'reading'|'cards'|null>>;online:boolean;syncStatus:SyncStatus;pendingCount:number;flush:()=>Promise<AppState>;syncNow:()=>Promise<void>;changeLanguage:(language:Language)=>void;addWord:(word:string,source?:string,meaning?:string)=>void;addSentence:(sentence:string,source?:string,translation?:string)=>void;addMistake:(area:string,pattern:string,original:string,correction:string,source?:string)=>void;applyAIMistakes:(mistakes:{area:string;pattern:string;original:string;correction:string}[])=>void};
const C=createContext<Context|null>(null);
export function useStudy(){const c=useContext(C);if(!c)throw new Error('Missing StudyProvider');return c;}
export function StudyProvider({children}:{children:React.ReactNode}){
 const [state,rawSetState]=useState(initialState),[page,setPage]=useState<Page>('Today'),[ready,setReady]=useState(false),[toast,setToast]=useState(''),[userId,setUserId]=useState<string|null>(null),[focusWord,setFocusWord]=useState<string|null>(null),[focusMode,setFocusMode]=useState<'reading'|'cards'|null>(null),[online,setOnline]=useState(true),[syncStatus,setSyncStatus]=useState<SyncStatus>('pending'),[pendingCount,setPendingCount]=useState(0),[tutorPrompt,setTutorPrompt]=useState(''),[sessionPaused,setSessionPaused]=useState(false);
 const stateRef=useRef(state),started=useRef(Date.now()),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null),engine=useRef<SyncEngine|null>(null),saveChain=useRef<Promise<void>>(Promise.resolve());
 const notify=useCallback((s:string)=>{setToast(s);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4200)},[]);
 const setState:React.Dispatch<React.SetStateAction<AppState>>=useCallback(action=>{rawSetState(previous=>{const next=typeof action==='function'?action(previous):action;return stampChanges(previous,next)})},[]);
 const dailySession=state.activeSession;const setDailySession:React.Dispatch<React.SetStateAction<DailySession|null>>=useCallback(action=>setState(s=>({...s,activeSession:typeof action==='function'?action(s.activeSession):action})),[setState]);
 useEffect(()=>{let active=true;async function start(){let local:AppState;try{const stored=await read<AppState>('state','learning');local=stored?migrateState(stored):loadState();if(!stored)local=await persistLearningState(local)}catch{local=loadState();notify('本地数据库暂时不可用，请检查浏览器存储权限。')}if(!active)return;stateRef.current=local;rawSetState(local);try{const daily=await read<DailySession>('meta','dailySession');const resumed=restoreDailySession(local,daily);if(resumed&&resumed.step>=0&&resumed.step<4){if(!local.activeSession)setDailySession(resumed);if(!resumed.done){if(resumed.language===local.profile.language)setPage(DAILY_STEPS[resumed.step]);else{setPage('Today');setSessionPaused(true)}}}}catch{}setReady(true);setOnline(network.isOnline());const hash=decodeURIComponent(location.hash.slice(1)) as Page;if(pages.includes(hash)&&!restoreDailySession(local,await read<DailySession>('meta','dailySession').catch(()=>null)))setPage(hash);const {data}=supabase?await supabase.auth.getSession().catch(()=>({data:{session:null}})):{data:{session:null}};if(active){setUserId(data.session?.user.id??null)}}void start();const change=()=>{const hash=decodeURIComponent(location.hash.slice(1)) as Page;if(pages.includes(hash)){const session=stateRef.current.activeSession;if(session&&!session.done)setSessionPaused(shouldPauseDailySession(session,hash,stateRef.current.profile.language));setPage(hash)}};window.addEventListener('hashchange',change);return()=>{active=false;window.removeEventListener('hashchange',change)}},[notify,setDailySession]);
 useEffect(()=>{if(!supabase)return;const {data}=supabase.auth.onAuthStateChange((_event,session)=>setUserId(session?.user.id??null));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{stateRef.current=state;document.documentElement.dataset.theme=state.theme;if(!ready)return;const snapshot=state,id=crypto.randomUUID();saveChain.current=saveChain.current.then(async()=>{await persistLearningState(snapshot,id);if(!network.isOnline())void requestBackgroundSync();const pending=await entries('queue');setPendingCount(pending.length);setSyncStatus('pending')}).catch(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(snapshot));notify('使用备用存储保存进度，恢复数据库后才能同步。')}catch{notify('无法保存学习记录，请立即导出数据。')}});const timer=setTimeout(()=>void saveChain.current.then(()=>engine.current?.sync()),900);return()=>clearTimeout(timer)},[state,ready,notify]);
 useEffect(()=>{if(!userId||!ready)return;const e=new SyncEngine(userId,()=>stateRef.current,merged=>{stateRef.current=merged;rawSetState(current=>{const safe=mergeStates(current,merged);return JSON.stringify(current)===JSON.stringify(safe)?current:safe})},status=>{setSyncStatus(status);void entries('queue').then(q=>setPendingCount(q.length))});engine.current=e;void e.sync();const unsub=network.subscribe(isOnline=>{setOnline(isOnline);if(isOnline)void e.sync()});const visible=()=>{if(!document.hidden)void e.sync()};document.addEventListener('visibilitychange',visible);const message=(event:MessageEvent)=>{if(event.data?.type==='SYNC_REQUESTED')void saveChain.current.then(()=>e.sync())};navigator.serviceWorker?.addEventListener('message',message);return()=>{e.dispose();unsub();document.removeEventListener('visibilitychange',visible);navigator.serviceWorker?.removeEventListener('message',message);engine.current=null}},[userId,ready]);
 useEffect(()=>{setOnline(network.isOnline());return network.subscribe(setOnline)},[]);
 useEffect(()=>{if(!ready)return;void write('meta','dailySession',dailySession);if(dailySession&&!dailySession.done&&!sessionPaused&&page!==DAILY_STEPS[dailySession.step]){setPage(DAILY_STEPS[dailySession.step]);setFocusMode(null)}},[dailySession,page,ready,sessionPaused]);
 const [currentDay,setCurrentDay]=useState(today);useEffect(()=>{const timer=setInterval(()=>setCurrentDay(today()),60000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(!ready)return;const key=`${currentDay}-${state.profile.language}`;if(!state.dailyPlans[key]||state.dailyPlans[key].minutes!==state.profile.dailyGoal)setState(s=>({...s,dailyPlans:{...s.dailyPlans,[key]:buildDailyPlan(s)}}))},[ready,currentDay,state.profile.language,state.profile.dailyGoal,state.dailyPlans,setState]);
 useEffect(()=>{const language=state.profile.language,key=`${currentDay}-${language}`,plan=state.dailyPlans[key];if(!ready||!userId||!online||dailySession||syncStatus!=='synced'||!plan||plan.generatedBy==='ai')return;async function personalize(){const requestId=await dailyPlanRequestId(userId!,currentDay,language,plan.minutes);const attempted=await read('meta',`ai-plan-${requestId}`);if(attempted)return;await write('meta',`ai-plan-${requestId}`,Date.now());try{const result=await aiProvider.request(`为 ${currentDay} 安排 ${plan.minutes} 分钟的个人学习。优先到期复习、反复出现的错误与薄弱语法。不要编造课程。`,{language},'daily_plan',requestId);if(result.plan)setState(s=>{const current=s.dailyPlans[key];return !current||current.minutes!==plan.minutes||current.generatedBy==='ai'?s:{...s,dailyPlans:{...s.dailyPlans,[key]:{...current,...result.plan!,generatedBy:'ai',at:Date.now()}}}})}catch{/* A usable rules-based plan remains available offline or without an AI key. */}}void personalize().catch(()=>{})},[ready,userId,online,currentDay,state.profile.language,state.dailyPlans,dailySession,syncStatus,setState]);
 useEffect(()=>{if(!ready||!state.settings.autoBackup)return;const key=`auto-${today()}`;void read('backups',key).then(existing=>{if(!existing)return write('backups',key,{at:Date.now(),state})}).catch(()=>notify('自动备份暂时未完成。'))},[state,ready,notify]);
 function navigate(p:Page){if(dailySession&&!dailySession.done)setSessionPaused(shouldPauseDailySession(dailySession,p,state.profile.language));setFocusMode(null);setPage(p);history.pushState(null,'',`#${encodeURIComponent(p)}`);started.current=Date.now();window.scrollTo({top:0,behavior:'instant'});stopSpeech()}
 function startDailySession(){if(dailySession&&!dailySession.done){if(dailySession.language!==state.profile.language)setState(s=>({...s,profile:{...s.profile,language:dailySession.language,level:s.languageProfiles[dailySession.language].level,goal:s.languageProfiles[dailySession.language].goal}}));navigate(DAILY_STEPS[dailySession.step]);setSessionPaused(false);return}setDailySession({language:state.profile.language,step:0,startedAt:Date.now(),baseline:state.sessions.length,completed:[],done:false});setSessionPaused(false);navigate('Review')}
 const completeDailyStep=useCallback((step:string)=>{setDailySession(s=>s&&!s.done&&DAILY_STEPS[s.step]===step?{...s,completed:[...new Set([...s.completed,DAILY_STEPS[s.step]])]}:s)},[setDailySession]);
 function advanceSession(){if(!dailySession||!dailySession.completed.includes(DAILY_STEPS[dailySession.step]))return;const next=advanceDailySession(dailySession);setDailySession(next);if(next.done)subtleFeedback();else{navigate(DAILY_STEPS[next.step]);setSessionPaused(false)}}
 function endSession(){if(dailySession?.done){setDailySession(null);setSessionPaused(false)}else setSessionPaused(true);setFocusMode(null);navigate('Today')}
 function record(type:string,count=1){const minutes=Math.max(0.1,Math.round((Date.now()-started.current)/6000)/10);setState(s=>({...s,sessions:[...s.sessions,{id:crypto.randomUUID(),day:today(),minutes,type,count,language:s.profile.language,at:Date.now()}]}));started.current=Date.now()}
 function save(id:string){setState(s=>({...s,saved:s.saved.includes(id)?s.saved.filter(x=>x!==id):[...s.saved,id]}))}
 function changeLanguage(language:Language){setSessionPaused(true);setState(s=>({...s,profile:{...s.profile,language,level:s.languageProfiles[language].level,goal:s.languageProfiles[language].goal}}))}
 function addWord(word:string,source='Quick capture',meaning=''){if(!word.trim())return;const captured=captureWord(word,state.profile.language,source,meaning);setState(s=>({...s,dictionary:{...s.dictionary,[captured.id]:s.dictionary[captured.id]??captured},saved:[...new Set([...s.saved,captured.id])]}));notify('已加入私人词典和复习队列。')}
 function addSentence(sentence:string,source='Quick capture',translation=''){if(!sentence.trim())return;const captured=captureSentence(sentence,state.profile.language,source,translation);setState(s=>({...s,sentences:s.sentences.some(x=>x.id===captured.id)?s.sentences:[...s.sentences,captured]}));notify('句子已保存。')}
 function addMistake(area:string,pattern:string,original:string,correction:string,source=area){const m=createMistake(state.profile.language,area,pattern,original,correction,source);setState(s=>({...s,mistakes:[...s.mistakes,m]}))}
 function applyAIMistakes(mistakes:{area:string;pattern:string;original:string;correction:string}[]){if(!mistakes.length)return;setState(s=>({...s,mistakes:[...s.mistakes,...mistakes.map(m=>createMistake(s.profile.language,m.area,m.pattern,m.original,m.correction,'AI feedback'))]}))}
 async function flush(){await saveChain.current;const committed=await persistLearningState(stateRef.current);stateRef.current=mergeStates(stateRef.current,committed);await write('meta','dailySession',stateRef.current.activeSession);return stateRef.current}
 const courseWords=coursePack(state.profile.language,state.profile.level).words;
 const custom=Object.values(state.dictionary).filter(w=>w.language===state.profile.language&&!courseWords.some(v=>v.id===w.id));
 return <C.Provider value={{state,setState,page,navigate,notify,save,record,speak:(text,rate,onEnd)=>speakText(text,state.profile.language==='ja'?'ja-JP':'en-US',rate??state.settings.audioRate,onEnd,notify),words:[...courseWords,...custom],focusWord,setFocusWord,userId,tutorPrompt,setTutorPrompt,ready,dailySession,sessionPaused,startDailySession,advanceSession,completeDailyStep,endSession,focusMode,setFocusMode,online,syncStatus,pendingCount,flush,syncNow:async()=>{await flush();const outcome=await engine.current?.drain();if(outcome!=='synced')throw new Error('进度已保存在此设备，但尚未完成云端同步。')},changeLanguage,addWord,addSentence,addMistake,applyAIMistakes}}>{ready?children:<div className="startup-splash"><span>k</span><strong>kotoba.</strong></div>}{toast&&<div role="status" className="toast">{toast}</div>}</C.Provider>
}
