'use client';
import {createContext,useContext,useEffect,useState,useRef,useCallback} from 'react';
import {initialState,loadState,migrateState,STORAGE_KEY,today,type AppState} from '@/lib/store';
import {supabase,supabaseConfiguration} from '@/lib/supabase';
import {verifiedOwnerForProject} from '@/lib/private-access';
import {DAILY_STEPS,advanceDailySession,restoreDailySession,shouldPauseDailySession,type DailySession} from '@/lib/daily-session';
import {type Word,type Language} from '@/lib/content';
import {coursePack} from '@/lib/course-library';
import {read,write,entries} from '@/lib/platform/storage';
import {network} from '@/lib/platform/network';
import {persistLearningState} from '@/lib/learning-storage';
import {speakText,stopSpeech} from '@/lib/platform/audio';
import {stampChanges,mergeStates} from '@/lib/sync-state';
import {SyncEngine,type SyncStatus} from '@/lib/sync-engine';
import {captureWord,captureSentence,createMistake,buildDailyPlan} from '@/lib/learning-memory';
import {aiProvider} from '@/lib/ai-provider';
import {dailyPlanRequestId} from '@/lib/daily-plan-request';
import {requestBackgroundSync} from '@/lib/platform/background-sync';
import {subtleFeedback} from '@/lib/platform/haptics';
import {saveStudyRecord} from '@/lib/study-record';
import {StudyTimer} from '@/lib/study-timer';
import {watchStudyTimer} from '@/lib/platform/study-lifecycle';
import {fetchCatalog} from '@/lib/content-library/client';
import {beginCourseSession,scopedSession,switchLearningScope,sessionSteps,sessionTask,finishCoreStep,saveSessionProgress} from '@/lib/content-library/daily-course-plan';
import {resolvedTheme} from '@/lib/theme';
export type {Page} from '@/lib/app-navigation';
import {pageFromHash,pageURL,type Page,type RouteOptions} from '@/lib/app-navigation';
type Context={state:AppState;setState:React.Dispatch<React.SetStateAction<AppState>>;page:Page;navigate:(p:Page,options?:RouteOptions)=>void;notify:(s:string)=>void;save:(id:string)=>void;record:(type:string,count?:number,language?:Language,operationId?:string)=>void;speak:(text:string,rate?:number,onEnd?:()=>void,language?:Language)=>void;words:Word[];focusWord:string|null;setFocusWord:React.Dispatch<React.SetStateAction<string|null>>;userId:string|null;tutorPrompt:string;setTutorPrompt:React.Dispatch<React.SetStateAction<string>>;ready:boolean;effectiveTheme:'light'|'dark';dailySession:DailySession|null;sessionPaused:boolean;startDailySession:()=>Promise<void>;startingSession:boolean;changeLevel:(level:string)=>void;advanceSession:()=>void;completeDailyStep:(step:string,courseId?:string)=>void;endSession:()=>void;focusMode:'reading'|'cards'|null;setFocusMode:React.Dispatch<React.SetStateAction<'reading'|'cards'|null>>;online:boolean;syncStatus:SyncStatus;pendingCount:number;localSaveStatus:'saving'|'saved'|'fallback'|'failed';flush:()=>Promise<AppState>;syncNow:()=>Promise<void>;changeLanguage:(language:Language)=>void;addWord:(word:string,source?:string,meaning?:string)=>void;addSentence:(sentence:string,source?:string,translation?:string)=>void;addMistake:(area:string,pattern:string,original:string,correction:string,source?:string)=>void;applyAIMistakes:(mistakes:{area:string;pattern:string;original:string;correction:string}[])=>void};
const C=createContext<Context|null>(null);
export function useStudy(){const c=useContext(C);if(!c)throw new Error('Missing StudyProvider');return c;}
export function StudyProvider({children}:{children:React.ReactNode}){
 const [state,rawSetState]=useState(initialState),[page,setPage]=useState<Page>('Today'),[ready,setReady]=useState(false),[toast,setToast]=useState(''),[userId,setUserId]=useState<string|null>(null),[focusWord,setFocusWord]=useState<string|null>(null),[focusMode,setFocusMode]=useState<'reading'|'cards'|null>(null),[online,setOnline]=useState(true),[syncStatus,setSyncStatus]=useState<SyncStatus>('pending'),[pendingCount,setPendingCount]=useState(0),[tutorPrompt,setTutorPrompt]=useState(''),[sessionPaused,setSessionPaused]=useState(false);
 const [startingSession,setStartingSession]=useState(false);const sessionStarting=useRef(false);
 const [localSaveStatus,setLocalSaveStatus]=useState<'saving'|'saved'|'fallback'|'failed'>('saving');const saveGeneration=useRef(0);
 const stateRef=useRef(state),started=useRef(new StudyTimer()),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null),engine=useRef<SyncEngine|null>(null),saveChain=useRef<Promise<void>>(Promise.resolve());
 const notify=useCallback((s:string)=>{setToast(s);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4200)},[]);
 const setState:React.Dispatch<React.SetStateAction<AppState>>=useCallback(action=>{rawSetState(previous=>{const next=typeof action==='function'?action(previous):action;return stampChanges(previous,next)})},[]);
 const [systemDark,setSystemDark]=useState(false);const effectiveTheme=resolvedTheme(state,systemDark);
 useEffect(()=>{const media=window.matchMedia('(prefers-color-scheme: dark)');const update=()=>setSystemDark(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=effectiveTheme},[effectiveTheme]);
 useEffect(()=>watchStudyTimer(started.current),[]);
 const dailySession=state.activeSession;const setDailySession:React.Dispatch<React.SetStateAction<DailySession|null>>=useCallback(action=>setState(s=>({...s,activeSession:typeof action==='function'?action(s.activeSession):action})),[setState]);
 useEffect(()=>{let active=true;async function start(){let local:AppState;try{const stored=await read<AppState>('state','learning');local=stored?migrateState(stored):loadState();if(!stored)local=await persistLearningState(local);setLocalSaveStatus('saved')}catch{local=loadState();setLocalSaveStatus('fallback');notify('本地数据库暂时不可用，请检查浏览器存储权限。')}if(!active)return;stateRef.current=local;rawSetState(local);try{const daily=await read<DailySession>('meta','dailySession');const resumed=restoreDailySession(local,daily);if(resumed&&resumed.step>=0&&resumed.step<4){if(!local.activeSession)setDailySession(resumed);if(!resumed.done){if(resumed.language===local.profile.language)setPage(DAILY_STEPS[resumed.step]);else{setPage('Today');setSessionPaused(true)}}}}catch{}setReady(true);setOnline(network.isOnline());const hash=pageFromHash(location.hash);if(hash){setPage(hash);setSessionPaused(shouldPauseDailySession(local.activeSession,hash,local.profile.language))}if(!network.isOnline()){const cached=verifiedOwnerForProject(await read('meta','verifiedOwner').catch(()=>undefined),supabaseConfiguration.ok?supabaseConfiguration.url:'');if(active)setUserId(cached?.id??null)}else{const {data}=supabase?await supabase.auth.getSession().catch(()=>({data:{session:null}})):{data:{session:null}};if(active)setUserId(data.session?.user.id??null)}}void start();const change=()=>{const hash=pageFromHash(location.hash);if(hash){const session=stateRef.current.activeSession;if(session&&!session.done)setSessionPaused(shouldPauseDailySession(session,hash,stateRef.current.profile.language));setPage(hash);setFocusMode(null);started.current.reset(!document.hidden);stopSpeech()}};window.addEventListener('hashchange',change);window.addEventListener('popstate',change);return()=>{active=false;window.removeEventListener('hashchange',change);window.removeEventListener('popstate',change)}},[notify,setDailySession]);
 useEffect(()=>{if(!supabase)return;const {data}=supabase.auth.onAuthStateChange((event,session)=>{if(!network.isOnline()&&event!=='SIGNED_OUT'&&!session)return;setUserId(session?.user.id??null)});return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{stateRef.current=state;if(!ready)return;const snapshot=state,id=crypto.randomUUID(),generation=++saveGeneration.current;setLocalSaveStatus('saving');saveChain.current=saveChain.current.then(async()=>{await persistLearningState(snapshot,id);if(generation===saveGeneration.current)setLocalSaveStatus('saved');if(!network.isOnline())void requestBackgroundSync();const pending=await entries('queue');setPendingCount(pending.length);setSyncStatus('pending')}).catch(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(snapshot));if(generation===saveGeneration.current)setLocalSaveStatus('fallback');notify('使用备用存储保存进度，恢复数据库后才能同步。')}catch{if(generation===saveGeneration.current)setLocalSaveStatus('failed');notify('无法保存学习记录，请立即导出数据。')}});const timer=setTimeout(()=>void saveChain.current.then(()=>engine.current?.sync()),900);return()=>clearTimeout(timer)},[state,ready,notify]);
 useEffect(()=>{if(!userId||!ready)return;const e=new SyncEngine(userId,()=>stateRef.current,merged=>{stateRef.current=merged;rawSetState(current=>{const safe=mergeStates(current,merged);return JSON.stringify(current)===JSON.stringify(safe)?current:safe})},status=>{setSyncStatus(status);void entries('queue').then(q=>setPendingCount(q.length))});engine.current=e;void e.sync();const unsub=network.subscribe(isOnline=>{setOnline(isOnline);if(isOnline)void saveChain.current.then(()=>e.sync())});const visible=()=>{if(!document.hidden)void saveChain.current.then(()=>e.sync())};document.addEventListener('visibilitychange',visible);window.addEventListener('pageshow',visible);const message=(event:MessageEvent)=>{if(event.data?.type==='SYNC_REQUESTED')void saveChain.current.then(()=>e.sync())};navigator.serviceWorker?.addEventListener('message',message);return()=>{e.dispose();unsub();document.removeEventListener('visibilitychange',visible);window.removeEventListener('pageshow',visible);navigator.serviceWorker?.removeEventListener('message',message);engine.current=null}},[userId,ready]);
 useEffect(()=>{setOnline(network.isOnline());return network.subscribe(setOnline)},[]);
 useEffect(()=>{if(!ready)return;void write('meta','dailySession',dailySession);if(dailySession&&!dailySession.done&&!sessionPaused&&page!==DAILY_STEPS[dailySession.step]){setPage(DAILY_STEPS[dailySession.step]);setFocusMode(null)}},[dailySession,page,ready,sessionPaused]);
 const [,refreshCalendar]=useState(0);const currentDay=today(state.profile.timezone);useEffect(()=>{const timer=setInterval(()=>refreshCalendar(value=>value+1),60000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(!ready)return;const key=`${currentDay}-${state.profile.language}`;if(!state.dailyPlans[key]||state.dailyPlans[key].minutes!==state.profile.dailyGoal)setState(s=>({...s,dailyPlans:{...s.dailyPlans,[key]:buildDailyPlan(s)}}))},[ready,currentDay,state.profile.language,state.profile.dailyGoal,state.dailyPlans,setState]);
 useEffect(()=>{const language=state.profile.language,key=`${currentDay}-${language}`,plan=state.dailyPlans[key];if(!ready||!userId||!online||dailySession||syncStatus!=='synced'||!plan||plan.generatedBy==='ai')return;async function personalize(){const requestId=await dailyPlanRequestId(userId!,currentDay,language,plan.minutes);const attempted=await read('meta',`ai-plan-${requestId}`);if(attempted)return;await write('meta',`ai-plan-${requestId}`,Date.now());try{const result=await aiProvider.request(`为 ${currentDay} 安排 ${plan.minutes} 分钟的个人学习。优先到期复习、反复出现的错误与薄弱语法。不要编造课程。`,{language},'daily_plan',requestId);if(result.plan)setState(s=>{const current=s.dailyPlans[key];return !current||current.minutes!==plan.minutes||current.generatedBy==='ai'?s:{...s,dailyPlans:{...s.dailyPlans,[key]:{...current,...result.plan!,generatedBy:'ai',at:Date.now()}}}})}catch{/* A usable rules-based plan remains available offline or without an AI key. */}}void personalize().catch(()=>{})},[ready,userId,online,currentDay,state.profile.language,state.dailyPlans,dailySession,syncStatus,setState]);
 useEffect(()=>{if(!ready||!state.settings.autoBackup)return;const key=`auto-${today(state.profile.timezone)}`;void read('backups',key).then(existing=>{if(!existing)return write('backups',key,{at:Date.now(),state})}).catch(()=>notify('自动备份暂时未完成。'))},[state,ready,notify]);
 function navigate(p:Page,options:RouteOptions={}){if(dailySession&&!dailySession.done)setSessionPaused(shouldPauseDailySession(dailySession,p,state.profile.language));setFocusMode(null);setPage(p);history.pushState({kotobaPage:p},'',pageURL(location.href,p,options));started.current.reset(!document.hidden);window.scrollTo({top:0,behavior:'instant'});stopSpeech()}
 async function startDailySession(){if(sessionStarting.current)return;sessionStarting.current=true;setStartingSession(true);try{const current=stateRef.current;const resumed=scopedSession(current);const catalog=resumed?[]:await fetchCatalog();const latest=stateRef.current;if(latest.profile.language!==current.profile.language||latest.profile.level!==current.profile.level){notify('学习范围已切换，请在当前范围重新开始。');return}const next=beginCourseSession(latest,catalog);setState(next);const session=next.activeSession!;const task=sessionTask(next,DAILY_STEPS[session.step]);navigate(DAILY_STEPS[session.step],task?{content:task.id,legacy:task.legacy}:{});setSessionPaused(false)}catch{notify('学习目录暂时无法加载。请联网重试，或打开已下载的资料；原学习记录保留。')}finally{sessionStarting.current=false;setStartingSession(false)}}
 const completeDailyStep=useCallback((step:string,courseId?:string)=>setState(s=>finishCoreStep(s,step,courseId)),[setState]);
 function advanceSession(){if(!dailySession||!dailySession.completed.includes(DAILY_STEPS[dailySession.step]))return;const steps=sessionSteps(state);const next=dailySession.step===steps.length-1?{...dailySession,done:true}:advanceDailySession(dailySession);setState(s=>saveSessionProgress(s,next));if(next.done)subtleFeedback();else{const task=sessionTask({...state,activeSession:next},DAILY_STEPS[next.step]);navigate(DAILY_STEPS[next.step],task?{content:task.id,legacy:task.legacy}:{});setSessionPaused(false)}}
 function endSession(){if(dailySession?.done){setDailySession(null);setSessionPaused(false)}else setSessionPaused(true);setFocusMode(null);navigate('Today')}
 function record(type:string,count=1,language=state.profile.language,operationId?:string){const minutes=Math.max(0.1,Math.round(started.current.take()/6000)/10);const id=operationId??crypto.randomUUID(),at=Date.now();setState(s=>saveStudyRecord(s,{id,day:today(s.profile.timezone,at),minutes,type,count,language,at}));started.current.reset(!document.hidden)}
 function save(id:string){setState(s=>({...s,saved:s.saved.includes(id)?s.saved.filter(x=>x!==id):[...s.saved,id]}))}
 function switchScope(language:Language,level?:string){stopSpeech();setFocusMode(null);setSessionPaused(true);setState(s=>switchLearningScope(s,language,level));history.replaceState({kotobaPage:page},'',pageURL(location.href,page));notify('原计划已暂停并保留。当前语言和等级使用独立计划，切换回来可继续。')}
 function changeLanguage(language:Language){if(language!==state.profile.language)switchScope(language)}
 function changeLevel(level:string){if(level!==state.profile.level)switchScope(state.profile.language,level)}
 function addWord(word:string,source='Quick capture',meaning=''){if(!word.trim())return;const captured=captureWord(word,state.profile.language,source,meaning);setState(s=>({...s,dictionary:{...s.dictionary,[captured.id]:s.dictionary[captured.id]??captured},saved:[...new Set([...s.saved,captured.id])]}));notify('已加入私人词典和复习队列。')}
 function addSentence(sentence:string,source='Quick capture',translation=''){if(!sentence.trim())return;const captured=captureSentence(sentence,state.profile.language,source,translation);setState(s=>({...s,sentences:s.sentences.some(x=>x.id===captured.id)?s.sentences:[...s.sentences,captured]}));notify('句子已保存。')}
 function addMistake(area:string,pattern:string,original:string,correction:string,source=area){const m=createMistake(state.profile.language,area,pattern,original,correction,source);setState(s=>({...s,mistakes:[...s.mistakes,m]}))}
 function applyAIMistakes(mistakes:{area:string;pattern:string;original:string;correction:string}[]){if(!mistakes.length)return;setState(s=>({...s,mistakes:[...s.mistakes,...mistakes.map(m=>createMistake(s.profile.language,m.area,m.pattern,m.original,m.correction,'AI feedback'))]}))}
 async function flush(){const generation=++saveGeneration.current;setLocalSaveStatus('saving');try{await saveChain.current;const committed=await persistLearningState(stateRef.current);stateRef.current=mergeStates(stateRef.current,committed);await write('meta','dailySession',stateRef.current.activeSession);const pending=await entries('queue');setPendingCount(pending.length);if(pending.length)setSyncStatus('pending');if(generation===saveGeneration.current)setLocalSaveStatus('saved');return stateRef.current}catch(error){let fallback=false;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(stateRef.current));fallback=true}catch{}if(generation===saveGeneration.current)setLocalSaveStatus(fallback?'fallback':'failed');throw error}}
 const courseWords=coursePack(state.profile.language,state.profile.level).words;
 const custom=Object.values(state.dictionary).filter(w=>w.language===state.profile.language&&!courseWords.some(v=>v.id===w.id));
 return <C.Provider value={{state,setState,page,navigate,notify,save,record,speak:(text,rate,onEnd,language)=>speakText(text,(language??state.profile.language)==='ja'?'ja-JP':'en-US',rate??state.settings.audioRate,onEnd,notify),words:[...courseWords,...custom],focusWord,setFocusWord,userId,tutorPrompt,setTutorPrompt,ready,effectiveTheme,dailySession,sessionPaused,startDailySession,startingSession,changeLevel,advanceSession,completeDailyStep,endSession,focusMode,setFocusMode,online,syncStatus,pendingCount,localSaveStatus,flush,syncNow:async()=>{await flush();const outcome=await engine.current?.drain();if(outcome!=='synced')throw new Error('进度已保存在此设备，但尚未完成云端同步。')},changeLanguage,addWord,addSentence,addMistake,applyAIMistakes}}>{ready?children:<div className="startup-splash"><span>k</span><strong>kotoba.</strong></div>}{toast&&<div role="status" className="toast">{toast}</div>}</C.Provider>
}
