export type Language='ja'|'en';
export type Word={id:string;word:string;pronunciation:string;meaning:string;example:string;translation:string;en?:string;tag:string;note?:string;related?:string;pos?:string;senses?:string[];collocations?:string[];synonyms?:string[];antonyms?:string[];topics?:string[];frequency?:'high'|'medium'|'low';register?:'neutral'|'informal'|'formal'|'academic';sourceRef?:string;usageNote?:string};
export const vocabulary:Record<Language,Word[]>={
ja:[
{id:'ja-yoyuu',word:'余裕',pronunciation:'よゆう',meaning:'余地 · 从容 · 充裕',example:'時間に余裕があります。',translation:'时间很充裕。',en:'I have plenty of time.',tag:'JLPT N3',related:'余裕を持つ / 心の余裕'},
{id:'ja-kikkake',word:'きっかけ',pronunciation:'きっかけ',meaning:'契机 · 起因 · 开端',example:'旅行が日本語を学ぶきっかけになりました。',translation:'旅行成为了我学习日语的契机。',en:'Travel inspired me to learn Japanese.',tag:'JLPT N3'},
{id:'ja-fuukei',word:'風景',pronunciation:'ふうけい',meaning:'风景 · 景色',example:'窓から美しい風景が見えます。',translation:'从窗户能看到美丽的风景。',tag:'JLPT N3'},
{id:'ja-omoiyari',word:'思いやり',pronunciation:'おもいやり',meaning:'体谅 · 关怀',example:'思いやりのある人になりたいです。',translation:'我想成为一个懂得体谅他人的人。',tag:'JLPT N3'},
{id:'ja-kurashi',word:'暮らし',pronunciation:'くらし',meaning:'生活 · 生计',example:'東京での暮らしに慣れました。',translation:'我已经习惯了东京的生活。',tag:'JLPT N3'},
{id:'ja-natsukashii',word:'懐かしい',pronunciation:'なつかしい',meaning:'令人怀念的',example:'この歌を聞くと、故郷が懐かしいです。',translation:'听到这首歌，就会怀念故乡。',tag:'JLPT N3'},
{id:'ja-kufuu',word:'工夫',pronunciation:'くふう',meaning:'用心设计 · 想办法',example:'毎日の勉強に工夫をしています。',translation:'我在每天的学习中尝试不同的方法。',tag:'JLPT N3'},
{id:'ja-tashika',word:'確か',pronunciation:'たしか',meaning:'确实 · 大概（记忆中）',example:'確か、明日は休みです。',translation:'如果没记错，明天休息。',tag:'JLPT N3'},
{id:'ja-shuukan',word:'習慣',pronunciation:'しゅうかん',meaning:'习惯',example:'毎朝、本を読む習慣があります。',translation:'我有每天早晨读书的习惯。',tag:'JLPT N3'},
{id:'ja-tsuzukeru',word:'続ける',pronunciation:'つづける',meaning:'继续 · 坚持',example:'少しずつ勉強を続けましょう。',translation:'让我们一点一点地坚持学习吧。',tag:'JLPT N4'}],
en:[
{id:'en-serendipity',word:'serendipity',pronunciation:'/ˌser.ənˈdɪp.ə.ti/',meaning:'偶然发现美好事物的运气',example:'Finding this little café was pure serendipity.',translation:'发现这家小咖啡馆，纯属美好的巧合。',tag:'C1 · noun',related:'a moment of serendipity / a serendipitous discovery',note:'源于 1754 年 Horace Walpole 创造的词，灵感来自《三个锡兰王子》。'},
{id:'en-take',word:'take',pronunciation:'/teɪk/',meaning:'拿 · 带 · 花费',example:'Take your time. There is no rush.',translation:'慢慢来，不用着急。',tag:'A1 · verb',related:'take off / take over / take advantage of'},
{id:'en-mindful',word:'mindful',pronunciation:'/ˈmaɪnd.fəl/',meaning:'留心的 · 有意识的',example:'Be mindful of the small moments.',translation:'留意生活中细小的瞬间。',tag:'B2 · adjective'},
{id:'en-perspective',word:'perspective',pronunciation:'/pəˈspek.tɪv/',meaning:'观点 · 视角',example:'Learning a language gives you a new perspective.',translation:'学习一门语言会给你一个新的视角。',tag:'B2 · noun'},
{id:'en-embrace',word:'embrace',pronunciation:'/ɪmˈbreɪs/',meaning:'拥抱 · 欣然接受',example:'Embrace the process of learning.',translation:'欣然接受学习的过程。',tag:'B2 · verb'},
{id:'en-subtle',word:'subtle',pronunciation:'/ˈsʌt.əl/',meaning:'微妙的 · 不易察觉的',example:'There is a subtle difference in meaning.',translation:'意思存在微妙的差别。',tag:'B2 · adjective'},
{id:'en-resilient',word:'resilient',pronunciation:'/rɪˈzɪl.i.ənt/',meaning:'有韧性的 · 能恢复的',example:'Small habits help us become more resilient.',translation:'小习惯帮助我们变得更有韧性。',tag:'C1 · adjective'},
{id:'en-curiosity',word:'curiosity',pronunciation:'/ˌkjʊə.riˈɒs.ə.ti/',meaning:'好奇心',example:'Let your curiosity guide you.',translation:'让好奇心指引你。',tag:'B1 · noun'},
{id:'en-thrive',word:'thrive',pronunciation:'/θraɪv/',meaning:'茁壮成长 · 兴旺',example:'Plants thrive in natural light.',translation:'植物在自然光下茁壮成长。',tag:'C1 · verb'},
{id:'en-intentional',word:'intentional',pronunciation:'/ɪnˈten.ʃən.əl/',meaning:'有意的 · 有目的的',example:'Make learning an intentional part of your day.',translation:'有意识地把学习融入每一天。',tag:'B2 · adjective'}]};
export const grammar={ja:{title:'〜わけではない',meaning:'并不是…… / 并非意味着……',structure:['Verb（普通形）+ わけではない','い-adjective + わけではない','な-adjective + な + わけではない'],explanation:'用于否定某个推断或过于笼统的判断。它不是完全否定，而是表达「并不全是如此」或「并不是因为这个原因」。常常和「だからといって」「いつも」「全部」搭配使用，让表达更有分寸。',example:'日本人だからといって、みんな寿司が好きなわけではない。',translation:'并不是所有日本人都喜欢寿司。',question:'「高いからといって、いい＿＿＿。」',options:['わけではない','わけがない','わけにはいかない'],answer:0},en:{title:'The present perfect',meaning:'过去发生、与现在有关',structure:['Subject + have / has + past participle','Subject + have / has + not + past participle'],explanation:'现在完成时连接过去与现在：它可以描述经历、刚刚完成的动作，或从过去持续到现在的状态。描述明确的过去时间（如 yesterday）时，通常使用一般过去时。',example:'I have lived in Tokyo for three years.',translation:'我已经在东京住了三年。（现在仍住在这里）',question:'I ____ this book already.',options:['have read','read yesterday','am read'],answer:0}};
export const articles={ja:{title:'小さな喫茶店、大きな幸せ',subtitle:'一间小咖啡馆，一份大幸福',category:'暮らし / LIFESTYLE',level:'N3',paragraphs:['東京の静かな通りに、小さな喫茶店があります。窓から朝の光が入り、コーヒーの香りが店の中に広がります。','忙しい毎日でも、ここでは時間に余裕を持つことができます。本を読んだり、風景を眺めたり。何もしない時間も、大切なのです。','幸せは、特別な出来事だけにあるわけではありません。日々の暮らしの中にある、小さな瞬間。それに気づく習慣を続けることが、大きな幸せにつながります。'],translations:['在东京安静的街道上，有一家小小的咖啡馆。晨光从窗户照进来，咖啡的香气弥漫在店内。','即使每天都很忙，在这里也可以从容地度过时间。读读书，看看风景。什么都不做的时间也很重要。','幸福并非只存在于特别的事情中。它也存在于日常生活中的细小瞬间。坚持留意这些瞬间，会带来很大的幸福。'],question:'作者认为，幸福来自哪里？',options:['只有特别的大事','日常生活中的小瞬间','繁忙的工作'],answer:1},en:{title:'The art of slowing down',subtitle:'慢下来，也是一种生活的艺术',category:'CULTURE / 生活方式',level:'B2',paragraphs:['On a quiet street in Tokyo, there is a small café. Morning light falls through its windows, and the smell of fresh coffee fills the room. Finding it felt like serendipity.','In a world that celebrates speed, slowing down can be an intentional choice. Take your time. Read a book. Watch the light change. Be mindful of the moments that might otherwise pass unnoticed.','Happiness does not always arrive as a grand event. Sometimes, it is a warm cup of coffee and a new perspective. Embrace these subtle moments, and let your curiosity guide you.'],translations:['在东京一条安静的街道上，有一家小咖啡馆。晨光穿过窗户，新鲜咖啡的香气弥漫在房间里。发现它就像一场美好的巧合。','在一个崇尚速度的世界中，慢下来可以是有意识的选择。慢慢来，读一本书，看光线变化，留心那些原本可能被忽略的瞬间。','幸福不总以盛大事件的形式出现。有时，它是一杯温热的咖啡与一个新视角。拥抱这些微妙的瞬间，让好奇心引领你。'],question:'What is the author encouraging?',options:['Working faster','Choosing to notice small moments','Avoiding new experiences'],answer:1}};
export const transcripts={ja:[{text:'いらっしゃいませ。ご注文はお決まりですか？',translation:'欢迎光临。您想好点什么了吗？'},{text:'はい、ホットコーヒーを一つお願いします。',translation:'是的，请给我一杯热咖啡。'},{text:'サイズはいかがなさいますか？',translation:'您要什么大小的？'},{text:'普通のサイズでお願いします。',translation:'请给我普通大小的。'},{text:'かしこまりました。少々お待ちください。',translation:'好的，请稍等。'}],en:[{text:'Good morning! What can I get for you?',translation:'早上好！您想点什么？'},{text:'Could I have a hot coffee, please?',translation:'请给我一杯热咖啡，好吗？'},{text:'Of course. What size would you like?',translation:'当然。您想要多大杯的？'},{text:'A regular size would be great, thank you.',translation:'普通大小就好，谢谢。'},{text:'Would you like anything else?',translation:'您还需要别的吗？'}]};
