import {articles,grammar,transcripts,vocabulary,type Language,type Word} from './content.ts';
import {extraArticles,extraEpisodes,extraGrammar,extraVocabulary,type GrammarLesson,type ReadingArticle,type ListeningEpisode} from './library-expansion.ts';
import {supplementalWords} from './vocabulary-supplement.ts';
import {expandedCoreWords} from './vocabulary-core-expansion.ts';
import {completionWords} from './vocabulary-level-completion.ts';

export const levels={ja:['N5','N4','N3','N2','N1'],en:['A1','A2','B1','B2','C1','C2']} as const;
export type CourseLevel=typeof levels.ja[number]|typeof levels.en[number];
type Seed={words:string;grammar:[string,string,string,string];reading:[string,string,string,string];listening:[string,string,string,string]};
// Original, level-aligned lessons. The JLPT does not publish an official fixed vocabulary list.
const seeds:Record<CourseLevel,Seed>={
 N5:{words:'私|わたし|我;あなた|あなた|你;今日|きょう|今天;明日|あした|明天;学校|がっこう|学校;先生|せんせい|老师;友達|ともだち|朋友;水|みず|水;本|ほん|书;食べる|たべる|吃;行く|いく|去;大きい|おおきい|大的',grammar:['です／ます','礼貌地陈述','私は学生です。','我是学生。'],reading:['はじめての学校','私は今日、新しい学校に行きます。先生はやさしいです。','今天我去新学校。老师很亲切。','学校'],listening:['自己紹介','こんにちは。私はミナです。','你好。我是美奈。','どうぞよろしくお願いします。|请多关照。']},
 N4:{words:'予定|よてい|计划;約束|やくそく|约定;便利|べんり|方便;静か|しずか|安静;運転|うんてん|驾驶;料理|りょうり|料理;病院|びょういん|医院;駅|えき|车站;急ぐ|いそぐ|赶忙;始める|はじめる|开始;忘れる|わすれる|忘记;必要|ひつよう|必要',grammar:['〜たことがある','表达过去的经历','京都へ行ったことがあります。','我去过京都。'],reading:['週末の予定','土曜日は友達と駅で会います。時間があれば、新しい店にも行きたいです。','星期六我和朋友在车站见面。如果有时间，也想去新店。','週末'],listening:['待ち合わせ','明日、何時に駅で会いますか。','明天几点在车站见面？','十時に会いましょう。|十点见吧。']},
 N3:{words:'経験|けいけん|经验;変化|へんか|变化;関係|かんけい|关系;印象|いんしょう|印象;相談|そうだん|商量;準備|じゅんび|准备;原因|げんいん|原因;結果|けっか|结果;普通|ふつう|普通;具体的|ぐたいてき|具体的;見直す|みなおす|重新审视;役立つ|やくだつ|有用',grammar:['〜ことにする','由自己决定做某事','毎日少しずつ読むことにしました。','我决定每天读一点。'],reading:['小さな習慣','新しい言葉を覚えるために、私は毎朝短い記事を読みます。続けると、少しずつ自信がつきます。','为了记住新词，我每天早晨读短文章。坚持下去，会逐渐建立信心。','習慣'],listening:['勉強の相談','日本語の勉強はどうですか。','日语学习怎么样？','毎日少しずつ続けています。|我每天都坚持学一点。']},
 N2:{words:'課題|かだい|课题;影響|えいきょう|影响;傾向|けいこう|趋势;改善|かいぜん|改善;判断|はんだん|判断;背景|はいけい|背景;制度|せいど|制度;効率|こうりつ|效率;柔軟|じゅうなん|灵活;相違|そうい|差异;維持|いじ|维持;促す|うながす|促使',grammar:['〜に伴って','随着某种变化而变化','働き方の変化に伴って、学び方も変わった。','随着工作方式变化，学习方式也改变了。'],reading:['働き方と学び方','働き方が多様になるにつれて、学習時間の確保が課題になっている。短い時間を活用する工夫が求められる。','随着工作方式日益多样，确保学习时间成为课题。需要想办法利用短暂时间。','学習'],listening:['学習計画の見直し','今の計画には、どんな課題がありますか。','目前的计划有什么问题？','時間の使い方を改善したいです。|我想改进时间安排。']},
 N1:{words:'示唆|しさ|启示;妥当|だとう|妥当;顕著|けんちょ|显著;概念|がいねん|概念;根拠|こんきょ|根据;検証|けんしょう|验证;認識|にんしき|认识;乖離|かいり|背离;曖昧|あいまい|模糊;網羅|もうら|涵盖;踏まえる|ふまえる|考虑到;裏付ける|うらづける|证实',grammar:['〜を踏まえて','以某项事实为依据','調査結果を踏まえて、方針を見直す。','根据调查结果重新审视方针。'],reading:['情報と判断','情報が豊富であることと、適切に判断できることは同義ではない。根拠を検証し、異なる見解を踏まえる姿勢が求められる。','信息丰富并不等于能做出恰当判断。需要核实依据，并考虑不同观点。','判断'],listening:['調査結果の検討','この結果から、何が示唆されますか。','这一结果说明了什么？','結論には追加の検証が必要です。|得出结论前还需要进一步验证。']},
 A1:{words:'hello|/həˈləʊ/|你好;name|/neɪm/|名字;home|/həʊm/|家;friend|/frend/|朋友;water|/ˈwɔːtə/|水;book|/bʊk/|书;school|/skuːl/|学校;today|/təˈdeɪ/|今天;tomorrow|/təˈmɒrəʊ/|明天;eat|/iːt/|吃;go|/ɡəʊ/|去;happy|/ˈhæpi/|高兴的',grammar:['Be: am, is, are','用 be 动词介绍人或事物','I am a student.','我是一名学生。'],reading:['My first day','My name is Mina. Today is my first day at school. My teacher is kind.','我叫美奈。今天是我上学的第一天。老师很亲切。','school'],listening:['Meeting a friend','Hello! My name is Mina.','你好！我叫美奈。','Nice to meet you.｜很高兴见到你。']},
 A2:{words:'appointment|/əˈpɔɪntmənt/|约会;ticket|/ˈtɪkɪt/|票;station|/ˈsteɪʃən/|车站;weather|/ˈweðə/|天气;weekend|/ˌwiːkˈend/|周末;usually|/ˈjuːʒuəli/|通常;decide|/dɪˈsaɪd/|决定;arrive|/əˈraɪv/|到达;early|/ˈɜːli/|早的;late|/leɪt/|迟的;quiet|/ˈkwaɪət/|安静的;useful|/ˈjuːsfəl/|有用的',grammar:['Past simple','讲述过去完成的事情','I visited my friend yesterday.','昨天我拜访了朋友。'],reading:['A weekend plan','We met at the station on Saturday. The weather was sunny, so we walked to a small park.','星期六我们在车站见面。天气晴朗，于是走去一个小公园。','weekend'],listening:['At the station','What time does the train leave?','火车几点出发？','It leaves at ten thirty.|十点半出发。']},
 B1:{words:'experience|/ɪkˈspɪəriəns/|经历;improve|/ɪmˈpruːv/|改善;opportunity|/ˌɒpəˈtjuːnəti/|机会;challenge|/ˈtʃælɪndʒ/|挑战;reason|/ˈriːzən/|原因;result|/rɪˈzʌlt/|结果;habit|/ˈhæbɪt/|习惯;confident|/ˈkɒnfɪdənt/|自信的;although|/ɔːlˈðəʊ/|虽然;prepare|/prɪˈpeə/|准备;consider|/kənˈsɪdə/|考虑;community|/kəˈmjuːnəti/|社区',grammar:['Present perfect for experience','谈论至今的人生经历','I have visited this city before.','我以前来过这个城市。'],reading:['Learning in small steps','Learning a language can feel difficult. However, short daily practice helps us build confidence over time.','学习语言可能让人觉得困难。但每天短时间练习能逐渐建立信心。','learning'],listening:['A learning routine','How do you practise English each day?','你每天怎样练习英语？','I read a short article on my way to work.|我上班路上读一篇短文。']},
 B2:{words:'approach|/əˈprəʊtʃ/|方法;assumption|/əˈsʌmpʃən/|假设;evaluate|/ɪˈvæljueɪt/|评估;evidence|/ˈevɪdəns/|证据;impact|/ˈɪmpækt/|影响;maintain|/meɪnˈteɪn/|维持;potential|/pəˈtenʃəl/|潜力;priority|/praɪˈɒrəti/|优先事项;reliable|/rɪˈlaɪəbəl/|可靠的;strategy|/ˈstrætədʒi/|策略;trend|/trend/|趋势;vary|/ˈveəri/|变化',grammar:['Passive voice in reports','突出过程或结果','The results were reviewed by the team.','结果由团队审查。'],reading:['Choosing useful information','We can access more information than ever before. The challenge is to evaluate sources and focus on evidence that helps us decide well.','我们能获取比以往更多的信息。挑战在于评估来源，关注有助于做出良好决定的证据。','information'],listening:['Discussing a proposal','What evidence supports this approach?','什么证据支持这种方法？','The trial results suggest it could work.|试验结果表明它可能有效。']},
 C1:{words:'ambiguous|/æmˈbɪɡjuəs/|模棱两可的;coherent|/kəʊˈhɪərənt/|连贯的;constraint|/kənˈstreɪnt/|限制;counterpart|/ˈkaʊntəpɑːt/|对应方;derive|/dɪˈraɪv/|源自;discrepancy|/dɪˈskrepənsi/|差异;implicit|/ɪmˈplɪsɪt/|隐含的;nuance|/ˈnjuːɑːns/|细微差别;plausible|/ˈplɔːzəbəl/|可信的;reinforce|/ˌriːɪnˈfɔːs/|强化;scope|/skəʊp/|范围;substantial|/səbˈstænʃəl/|相当大的',grammar:['Inversion for emphasis','用倒装突出限制或结果','Only then did we understand the problem.','直到那时我们才理解问题。'],reading:['When evidence disagrees','Two plausible studies may reach different conclusions because their scope and assumptions differ. A careful reader examines those constraints before deciding.','两项看似可信的研究可能因范围和假设不同而得出不同结论。审慎的读者会先检查这些限制。','evidence'],listening:['Interpreting the findings','There is a discrepancy between the reports.','两份报告之间存在差异。','Could the sample size explain it?|样本规模能解释这个差异吗？']},
 C2:{words:'acquiesce|/ˌækwiˈes/|默许;conjecture|/kənˈdʒektʃə/|推测;corroborate|/kəˈrɒbəreɪt/|证实;equivocal|/ɪˈkwɪvəkəl/|含糊的;incongruous|/ɪnˈkɒŋɡruəs/|不协调的;lucid|/ˈluːsɪd/|清晰的;mitigate|/ˈmɪtɪɡeɪt/|减轻;nuanced|/ˈnjuːɑːnst/|细致入微的;paradox|/ˈpærədɒks/|悖论;premise|/ˈpremɪs/|前提;reconcile|/ˈrekənsaɪl/|调和;tenuous|/ˈtenjuəs/|牵强的',grammar:['Concessive clauses','承认限制后提出判断','However compelling the theory, the evidence remains equivocal.','无论理论多么有说服力，证据仍然含糊。'],reading:['The limits of certainty','A lucid argument can still rest on a tenuous premise. To reconcile conflicting accounts, we must examine what each source can actually corroborate.','清晰的论证仍可能建立在薄弱前提上。要调和相互矛盾的叙述，必须检视各来源真正能证实什么。','argument'],listening:['A careful conclusion','The premise sounds plausible, but is it corroborated?','这个前提听起来可信，但有证据支持吗？','We should distinguish conjecture from established fact.|我们应区分推测和既定事实。']}
};
const levelOf=(tag:string,language:Language)=>levels[language].find(level=>new RegExp(`\\b${level}\\b`).test(tag));
function wordRows(level:CourseLevel,language:Language):Word[]{return seeds[level].words.split(';').map((row,index)=>{const [word,pronunciation,meaning]=row.split('|');const sentence=language==='ja'?`${word}について学びます。`:`We are learning about ${word}.`;return {id:`course-${language}-${level.toLowerCase()}-${index+1}`,word,pronunciation,meaning,example:sentence,translation:language==='ja'?`学习「${meaning}」的用法。`:`我们正在学习「${meaning}」。`,tag:`${language==='ja'?'JLPT ':''}${level}`}})}
function seedGrammar(level:CourseLevel):GrammarLesson{const [title,meaning,example,translation]=seeds[level].grammar;return {id:`course-grammar-${level.toLowerCase()}`,level,title,meaning,structure:[title],explanation:meaning,example,translation,question:`选择与「${meaning}」相符的句子。`,options:[example,level.startsWith('N')?'これは不自然な表現です。':'This sentence is unrelated.'],answer:0}}
function seedArticle(level:CourseLevel):ReadingArticle{const [title,paragraph,translation,topic]=seeds[level].reading;return {id:`course-article-${level.toLowerCase()}`,title,subtitle:topic,category:'COURSE READING',level,paragraphs:[paragraph],translations:[translation],question:level.startsWith('N')?'文章の話題は何ですか。':'What is the main topic?',options:[topic,level.startsWith('N')?'天気予報':'A weather report'],answer:0,summary:translation}}
function seedEpisode(level:CourseLevel):ListeningEpisode{const [title,first,translation,second]=seeds[level].listening;const separator=second.includes('｜')?'｜':'|';const [text,translated]=second.split(separator);return {id:`course-episode-${level.toLowerCase()}`,title,description:'短い会話 · Short conversation',level,lines:[{text:first,translation},{text,translation:translated}]}}
export function coursePack(language:Language,requested:string){const level=(levels[language] as readonly string[]).includes(requested)?requested as CourseLevel:levels[language][0];const legacyReadingLevel=language==='ja'?'N3':'B2';const legacyGrammarLevel=language==='ja'?'N3':'B1';const words=[...wordRows(level,language),...supplementalWords(language,level),...vocabulary[language].filter(w=>levelOf(w.tag,language)===level),...extraVocabulary[language].filter(w=>levelOf(w.tag,language)===level),...expandedCoreWords(language,level),...completionWords(language,level)];const grammars=[seedGrammar(level),...extraGrammar[language].filter(g=>g.level===level),...(level===legacyGrammarLevel?[{...grammar[language],id:`grammar-${language}`,level}]:[])];const readings=[seedArticle(level),...extraArticles[language].filter(a=>a.level===level),...(level===legacyReadingLevel?[{...articles[language],id:`article-${language}`,summary:articles[language].translations.join(' ')}]:[])];const episodes=[seedEpisode(level),...extraEpisodes[language].filter(e=>e.level===level),...(level===legacyGrammarLevel?[{id:`episode-${language}`,title:'A coffee in Tokyo',description:'Everyday conversation',level,lines:transcripts[language]}]:[])];return {level,words,grammars,readings,episodes}}
export function allCourseWords(language:Language){return levels[language].flatMap(level=>coursePack(language,level).words)}
