import {type Language} from './content.ts';
import {allCourseWords,coursePack} from './course-library.ts';
import {today,type AppState,type DailyPlan,type Mistake,type Sentence,type SavedWord} from './store.ts';
// Non-secret 128-bit client keys avoid short-hash collisions as the personal library grows.
// PostgreSQL uses a separate canonical UUID for each client key.
export function stableId(prefix:string,value:string){let a=1779033703,b=3144134277,c=1013904242,d=2773480762;for(const char of value.normalize('NFC')){const k=char.codePointAt(0)!;a=b^Math.imul(a^k,597399067);b=c^Math.imul(b^k,2869860233);c=d^Math.imul(c^k,951274213);d=a^Math.imul(d^k,2716044179)}a=Math.imul(c^(a>>>18),597399067);b=Math.imul(d^(b>>>22),2869860233);c=Math.imul(a^(c>>>17),951274213);d=Math.imul(b^(d>>>19),2716044179);return `${prefix}-${[a^b^c^d,b^a,c^a,d^a].map(n=>(n>>>0).toString(16).padStart(8,'0')).join('')}`;}
export function captureWord(word:string,language:Language,source='Quick capture',meaning=''):SavedWord{const normalized=word.trim().normalize('NFC');const known=allCourseWords(language).find(w=>w.word.toLowerCase()===normalized.toLowerCase());return {...known,id:known?.id??stableId(`word-${language}`,normalized.toLowerCase()),word:normalized,pronunciation:known?.pronunciation??'',meaning:meaning||known?.meaning||'待补充释义',example:known?.example??'',translation:known?.translation??'',tag:known?.tag??'Personal word',language,source,firstSeen:Date.now(),tags:[]};}
export function captureSentence(sentence:string,language:Language,source:string,translation=''):Sentence{const normalized=sentence.trim().normalize('NFC');return {id:stableId(`sentence-${language}`,normalized),sentence:normalized,translation,source,language,date:Date.now(),notes:'',vocabulary:[],grammar:[]};}
export function createMistake(language:Language,area:string,pattern:string,original:string,correction:string,source=area):Mistake{return {id:crypto.randomUUID(),language,area,pattern,original,correction,source,at:Date.now(),resolved:false};}
export function mistakePatterns(state:AppState,language:Language){const map=new Map<string,{pattern:string;count:number;last:number;example:Mistake}>();for(const m of state.mistakes.filter(m=>m.language===language&&!m.resolved)){const p=map.get(m.pattern);map.set(m.pattern,{pattern:m.pattern,count:(p?.count??0)+1,last:Math.max(p?.last??0,m.at),example:m})}return [...map.values()].sort((a,b)=>b.count-a.count||b.last-a.last);}
export function buildDailyPlan(state:AppState,language=state.profile.language):DailyPlan{const core=coursePack(language,state.languageProfiles[language].level).words;const words=[...core,...Object.values(state.dictionary).filter(w=>w.language===language&&!core.some(v=>v.id===w.id))];const due=words.filter(w=>!state.reviews[w.id]||state.reviews[w.id].due<=Date.now());const weak=mistakePatterns(state,language).slice(0,3).map(m=>m.pattern);return {day:today(),language,minutes:state.profile.dailyGoal,focus:weak[0]??'Natural conversation',reason:weak.length?'根据近期反复出现的错误，优先巩固薄弱表达。':'结合到期复习与日常输出，保持均衡的学习节奏。',generatedBy:'rules',reviewCount:due.length,weak,at:Date.now()};}
export function learningContext(state:AppState,question:string){const lang=state.profile.language;const p=state.languageProfiles[lang];const words=[...coursePack(lang,p.level).words,...Object.values(state.dictionary).filter(w=>w.language===lang)];const related=words.filter(w=>question.toLowerCase().includes(w.word.toLowerCase())||question.includes(w.meaning));const relevant=related.length?related:words.filter(w=>state.reviews[w.id]?.lapses>0).slice(0,8);return {language:lang,profiles:state.languageProfiles,goal:p.goal,interests:p.interests,known:words.filter(w=>state.reviews[w.id]?.repetitions>1).map(w=>w.word).slice(0,50),learning:relevant.map(w=>({word:w.word,meaning:w.meaning})),grammar:state.completed.filter(x=>x.startsWith(lang+':')),mistakes:mistakePatterns(state,lang).slice(0,5).map(m=>({pattern:m.pattern,count:m.count,original:m.example.original,correction:m.example.correction})),recentReading:Object.entries(state.readingPositions).filter(([id])=>id.includes(lang)).slice(-3),recentSpeaking:state.speakingHistory.filter(s=>s.language===lang).slice(-3).map(s=>({text:s.text,feedback:s.feedback.slice(0,500)})),recentReviews:state.reviewHistory.filter(r=>r.language===lang).slice(-8),savedSentences:state.sentences.filter(s=>s.language===lang).slice(-5).map(s=>s.sentence)};}
