import type {Language,Word} from './content.ts';
import type {AppState} from './store.ts';

export type LexiconMeta={level:string;partOfSpeech:string;senses:string[];collocations:string[];synonyms:string[];antonyms:string[];topics:string[];frequency:'high'|'medium'|'low';register:'neutral'|'informal'|'formal'|'academic';source:string};
export type LearningSignals={reviewCount:number;repetitions:number;lapses:number;passiveMastery:number;activeEvidence:number;activeMastery:number;lastReviewed:number|null;readingEvidence:number;speakingEvidence:number};

const levelPattern=/\b(N[1-5]|A[12]|B[12]|C[12])\b/;
export function wordLevel(word:Word){return word.tag.match(levelPattern)?.[1]??'Personal';}
function inferredFrequency(level:string):LexiconMeta['frequency']{if(['N5','N4','A1','A2'].includes(level))return 'high';if(['N3','N2','B1','B2'].includes(level))return 'medium';return 'low';}
function inferredRegister(level:string):LexiconMeta['register']{return ['N1','C1','C2'].includes(level)?'academic':'neutral';}
function sourceOf(word:Word){if(word.sourceRef)return word.sourceRef;if(word.id.startsWith('complete-'))return 'V2.5.2 level completion';if(word.id.startsWith('lex-'))return 'V2.5.1 core expansion';if(word.id.startsWith('supp-'))return 'V2.5 supplement';if(word.id.startsWith('course-'))return 'Course seed';if(word.id.startsWith('ja-')||word.id.startsWith('en-'))return 'Starter content';return 'Library content';}
export function lexiconMeta(word:Word):LexiconMeta{const level=wordLevel(word);const taggedPos=word.tag.split('·')[1]?.trim();return {level,partOfSpeech:word.pos??taggedPos??'word',senses:word.senses?.length?word.senses:word.meaning.split(/[·；;]/).map(x=>x.trim()).filter(Boolean),collocations:word.collocations?.length?word.collocations:(word.related??'').split('/').map(x=>x.trim()).filter(Boolean),synonyms:word.synonyms??[],antonyms:word.antonyms??[],topics:word.topics?.length?word.topics:['core'],frequency:word.frequency??inferredFrequency(level),register:word.register??inferredRegister(level),source:sourceOf(word)};}
function includesWord(text:string,word:string){return Boolean(text)&&text.toLocaleLowerCase().includes(word.toLocaleLowerCase());}
export function learningSignals(word:Word,state:AppState):LearningSignals{const review=state.reviews[word.id];const history=state.reviewHistory.filter(item=>item.cardId===word.id);const saved=state.dictionary[word.id];const speakingEvidence=state.speakingHistory.filter(item=>includesWord(item.text,word.word)).length;const sentenceEvidence=state.sentences.filter(item=>item.vocabulary.some(v=>v.toLocaleLowerCase()===word.word.toLocaleLowerCase())||includesWord(item.sentence,word.word)).length;const readingEvidence=saved&&/reading/i.test(saved.source)?1:0;const repetitions=review?.repetitions??0,lapses=review?.lapses??0;const passiveMastery=Math.max(0,Math.min(100,repetitions*18-lapses*8+(review?.interval??0)));const activeEvidence=speakingEvidence+sentenceEvidence;const activeMastery=Math.max(0,Math.min(100,activeEvidence*25+Math.min(25,repetitions*4)));return {reviewCount:history.length,repetitions,lapses,passiveMastery,activeEvidence,activeMastery,lastReviewed:history.at(-1)?.at??null,readingEvidence,speakingEvidence};}
export function canonicalVocabulary(words:Word[],preferredIds=new Set<string>()){const best=new Map<string,Word>();const score=(w:Word)=>{const meta=lexiconMeta(w);return (preferredIds.has(w.id)?1000:0)+(w.example?4:0)+(w.related?3:0)+(meta.partOfSpeech!=='word'?2:0)+(w.sourceRef?1:0);};for(const word of words){const key=word.word.trim().normalize('NFC').toLocaleLowerCase();const current=best.get(key);if(!current||score(word)>score(current))best.set(key,word);}return [...best.values()];}
