import type {Language,Word} from './content.ts';

// V2.5.1 vocabulary quality expansion.
// Entries use semantic, stable IDs so existing SRS card IDs remain untouched.
// Level placement is pedagogical guidance; JLPT/CEFR do not define a single official fixed word list.
export const coreVocabularyExpansion:Record<Language,Word[]>={
 ja:[
  {id:'lex-ja-n5-jikan',word:'時間',pronunciation:'じかん',meaning:'时间',example:'時間がありますか。',translation:'你有时间吗？',tag:'JLPT N5 · 名词',related:'時間がある / 時間を使う'},
  {id:'lex-ja-n5-shigoto',word:'仕事',pronunciation:'しごと',meaning:'工作',example:'父は毎日仕事に行きます。',translation:'爸爸每天去上班。',tag:'JLPT N5 · 名词',related:'仕事をする / 仕事に行く'},
  {id:'lex-ja-n5-densha',word:'電車',pronunciation:'でんしゃ',meaning:'电车',example:'電車で学校へ行きます。',translation:'我坐电车去学校。',tag:'JLPT N5 · 名词',related:'電車に乗る / 電車を降りる'},
  {id:'lex-ja-n5-kuruma',word:'車',pronunciation:'くるま',meaning:'汽车',example:'車でスーパーへ行きます。',translation:'我开车去超市。',tag:'JLPT N5 · 名词',related:'車に乗る / 車を運転する'},
  {id:'lex-ja-n5-nomu',word:'飲む',pronunciation:'のむ',meaning:'喝',example:'朝、水を飲みます。',translation:'早上我喝水。',tag:'JLPT N5 · 动词',related:'水を飲む / 薬を飲む'},
  {id:'lex-ja-n5-yomu',word:'読む',pronunciation:'よむ',meaning:'读；阅读',example:'夜に本を読みます。',translation:'我晚上读书。',tag:'JLPT N5 · 动词',related:'本を読む / 新聞を読む'},
  {id:'lex-ja-n5-kaku',word:'書く',pronunciation:'かく',meaning:'写',example:'ノートに名前を書いてください。',translation:'请把名字写在笔记本上。',tag:'JLPT N5 · 动词',related:'名前を書く / 手紙を書く'},
  {id:'lex-ja-n5-au',word:'会う',pronunciation:'あう',meaning:'见；见面',example:'駅で友達に会います。',translation:'我在车站见朋友。',tag:'JLPT N5 · 动词',related:'友達に会う / 初めて会う'},
  {id:'lex-ja-n5-kuru',word:'来る',pronunciation:'くる',meaning:'来',example:'明日、友達が家に来ます。',translation:'明天朋友来我家。',tag:'JLPT N5 · 动词',related:'家に来る / 日本に来る'},
  {id:'lex-ja-n5-kaeru',word:'帰る',pronunciation:'かえる',meaning:'回去；回家',example:'六時に家へ帰ります。',translation:'我六点回家。',tag:'JLPT N5 · 动词',related:'家に帰る / 国へ帰る'},
  {id:'lex-ja-n4-seikatsu',word:'生活',pronunciation:'せいかつ',meaning:'生活',example:'日本での生活に慣れてきました。',translation:'我逐渐习惯了在日本的生活。',tag:'JLPT N4 · 名词',related:'生活に慣れる / 日常生活'},
  {id:'lex-ja-n4-bunka',word:'文化',pronunciation:'ぶんか',meaning:'文化',example:'旅行すると、その国の文化を知ることができます。',translation:'旅行时可以了解那个国家的文化。',tag:'JLPT N4 · 名词',related:'日本文化 / 文化の違い'},
  {id:'lex-ja-n4-saikin',word:'最近',pronunciation:'さいきん',meaning:'最近',example:'最近、朝早く起きるようになりました。',translation:'最近我开始早起了。',tag:'JLPT N4 · 副词·名词',related:'最近では / 最近のニュース'},
  {id:'lex-ja-n4-saisho',word:'最初',pronunciation:'さいしょ',meaning:'最初；一开始',example:'最初は難しかったですが、少しずつ慣れました。',translation:'一开始很难，但我慢慢习惯了。',tag:'JLPT N4 · 名词·副词',related:'最初から / 最初の一歩'},
  {id:'lex-ja-n4-saigo',word:'最後',pronunciation:'さいご',meaning:'最后',example:'最後まで話を聞いてください。',translation:'请把话听到最后。',tag:'JLPT N4 · 名词',related:'最後まで / 最後の日'},
  {id:'lex-ja-n4-tochuu',word:'途中',pronunciation:'とちゅう',meaning:'途中；中途',example:'学校へ行く途中で雨が降りました。',translation:'去学校的路上下雨了。',tag:'JLPT N4 · 名词',related:'途中で / 帰る途中'},
  {id:'lex-ja-n4-kimeru',word:'決める',pronunciation:'きめる',meaning:'决定',example:'週末の予定を今日決めます。',translation:'今天决定周末的安排。',tag:'JLPT N4 · 动词',related:'予定を決める / 自分で決める'},
  {id:'lex-ja-n4-kaeru-change',word:'変える',pronunciation:'かえる',meaning:'改变；更换',example:'勉強の方法を少し変えました。',translation:'我稍微改变了学习方法。',tag:'JLPT N4 · 动词',related:'予定を変える / 考えを変える'},
  {id:'lex-ja-n4-tsuzuku',word:'続く',pronunciation:'つづく',meaning:'持续；继续',example:'雨は明日まで続くそうです。',translation:'听说明天还会继续下雨。',tag:'JLPT N4 · 动词',related:'長く続く / 会議が続く'},
  {id:'lex-ja-n4-todoku',word:'届く',pronunciation:'とどく',meaning:'送到；到达',example:'注文した本が昨日届きました。',translation:'订的书昨天送到了。',tag:'JLPT N4 · 动词',related:'荷物が届く / 声が届く'},
  {id:'lex-ja-n3-joukyou',word:'状況',pronunciation:'じょうきょう',meaning:'状况；情况',example:'まず現在の状況を確認しましょう。',translation:'先确认一下目前的情况吧。',tag:'JLPT N3 · 名词',related:'状況を確認する / 状況が変わる'},
  {id:'lex-ja-n3-houhou',word:'方法',pronunciation:'ほうほう',meaning:'方法',example:'もっと効率のいい方法を探しています。',translation:'我在寻找更高效的方法。',tag:'JLPT N3 · 名词',related:'方法を選ぶ / 学習方法'},
  {id:'lex-ja-n3-naiyou',word:'内容',pronunciation:'ないよう',meaning:'内容',example:'メールの内容をもう一度確認しました。',translation:'我再次确认了邮件内容。',tag:'JLPT N3 · 名词',related:'内容を確認する / 授業内容'},
  {id:'lex-ja-n3-mokuteki',word:'目的',pronunciation:'もくてき',meaning:'目的',example:'旅行の目的は友達に会うことです。',translation:'旅行的目的是去见朋友。',tag:'JLPT N3 · 名词',related:'目的を達成する / 目的地'},
  {id:'lex-ja-n3-tachiba',word:'立場',pronunciation:'たちば',meaning:'立场；处境',example:'相手の立場で考えることも大切です。',translation:'站在对方的立场思考也很重要。',tag:'JLPT N3 · 名词',related:'立場を理解する / 立場が違う'},
  {id:'lex-ja-n3-sekinin',word:'責任',pronunciation:'せきにん',meaning:'责任',example:'自分の仕事には責任を持ちたいです。',translation:'我想对自己的工作负责。',tag:'JLPT N3 · 名词',related:'責任を持つ / 責任がある'},
  {id:'lex-ja-n3-fueru',word:'増える',pronunciation:'ふえる',meaning:'增加',example:'外国からの観光客が増えています。',translation:'来自国外的游客正在增加。',tag:'JLPT N3 · 动词',related:'数が増える / 機会が増える'},
  {id:'lex-ja-n3-heru',word:'減る',pronunciation:'へる',meaning:'减少',example:'毎日歩くと、ストレスが少し減ります。',translation:'每天走路的话，压力会稍微减轻。',tag:'JLPT N3 · 动词',related:'数が減る / 人が減る'},
  {id:'lex-ja-n3-kuraberu',word:'比べる',pronunciation:'くらべる',meaning:'比较',example:'二つのプランを比べてから決めます。',translation:'比较两个方案后再决定。',tag:'JLPT N3 · 动词',related:'AとBを比べる / 値段を比べる'},
  {id:'lex-ja-n3-tashikameru',word:'確かめる',pronunciation:'たしかめる',meaning:'确认；查清',example:'出発前に時間を確かめてください。',translation:'出发前请确认时间。',tag:'JLPT N3 · 动词',related:'事実を確かめる / もう一度確かめる'},
  {id:'lex-ja-n2-genjou',word:'現状',pronunciation:'げんじょう',meaning:'现状',example:'まず現状を正しく理解する必要があります。',translation:'首先有必要正确理解现状。',tag:'JLPT N2 · 名词',related:'現状を把握する / 現状を改善する'},
  {id:'lex-ja-n2-taishou',word:'対象',pronunciation:'たいしょう',meaning:'对象；目标范围',example:'この調査は大学生を対象に行われました。',translation:'这项调查以大学生为对象进行。',tag:'JLPT N2 · 名词',related:'対象になる / 調査対象'},
  {id:'lex-ja-n2-houshin',word:'方針',pronunciation:'ほうしん',meaning:'方针',example:'会社は新しい方針を発表しました。',translation:'公司公布了新方针。',tag:'JLPT N2 · 名词',related:'方針を決める / 基本方針'},
  {id:'lex-ja-n2-shudan',word:'手段',pronunciation:'しゅだん',meaning:'手段',example:'目的に合った手段を選ぶべきです。',translation:'应该选择符合目的的手段。',tag:'JLPT N2 · 名词',related:'手段を選ぶ / 交通手段'},
  {id:'lex-ja-n2-hyouka',word:'評価',pronunciation:'ひょうか',meaning:'评价',example:'結果だけでなく過程も評価されました。',translation:'不仅结果，过程也得到了评价。',tag:'JLPT N2 · 名词',related:'評価する / 高い評価'},
  {id:'lex-ja-n2-jitsugen',word:'実現',pronunciation:'じつげん',meaning:'实现',example:'長年の計画がようやく実現しました。',translation:'多年的计划终于实现了。',tag:'JLPT N2 · 名词',related:'実現する / 夢の実現'},
  {id:'lex-ja-n2-mitomeru',word:'認める',pronunciation:'みとめる',meaning:'承认；认可',example:'自分の間違いを認めるのは大切です。',translation:'承认自己的错误很重要。',tag:'JLPT N2 · 动词',related:'事実を認める / 能力を認める'},
  {id:'lex-ja-n2-motomeru',word:'求める',pronunciation:'もとめる',meaning:'寻求；要求',example:'利用者はより分かりやすい説明を求めています。',translation:'用户希望得到更易懂的说明。',tag:'JLPT N2 · 动词',related:'助けを求める / 改善を求める'},
  {id:'lex-ja-n2-fusegu',word:'防ぐ',pronunciation:'ふせぐ',meaning:'防止；预防',example:'小さな確認で大きなミスを防げます。',translation:'通过简单确认可以防止重大失误。',tag:'JLPT N2 · 动词',related:'事故を防ぐ / ミスを防ぐ'},
  {id:'lex-ja-n2-fukumu',word:'含む',pronunciation:'ふくむ',meaning:'包含',example:'料金には朝食も含まれています。',translation:'费用中也包含早餐。',tag:'JLPT N2 · 动词',related:'〜を含む / 水分を含む'},
  {id:'lex-ja-n1-shushi',word:'趣旨',pronunciation:'しゅし',meaning:'主旨；宗旨',example:'提案の趣旨を簡潔に説明してください。',translation:'请简要说明提案的主旨。',tag:'JLPT N1 · 名词',related:'趣旨を説明する / 趣旨に沿う'},
  {id:'lex-ja-n1-kenen',word:'懸念',pronunciation:'けねん',meaning:'担忧；顾虑',example:'新制度にはいくつかの懸念が残っています。',translation:'新制度仍存在一些担忧。',tag:'JLPT N1 · 名词',related:'懸念がある / 懸念を示す'},
  {id:'lex-ja-n1-ronten',word:'論点',pronunciation:'ろんてん',meaning:'论点',example:'議論の論点を整理してから結論を出します。',translation:'整理讨论要点后再下结论。',tag:'JLPT N1 · 名词',related:'論点を整理する / 主要な論点'},
  {id:'lex-ja-n1-kainyuu',word:'介入',pronunciation:'かいにゅう',meaning:'介入；干预',example:'政府の介入が市場に影響を与えました。',translation:'政府的干预对市场产生了影响。',tag:'JLPT N1 · 名词',related:'介入する / 過度な介入'},
  {id:'lex-ja-n1-chikuseki',word:'蓄積',pronunciation:'ちくせき',meaning:'积累',example:'長年の経験の蓄積が判断を支えています。',translation:'多年的经验积累支撑着判断。',tag:'JLPT N1 · 名词',related:'知識を蓄積する / データの蓄積'},
  {id:'lex-ja-n1-suikou',word:'遂行',pronunciation:'すいこう',meaning:'执行；完成',example:'限られた時間で任務を遂行しました。',translation:'在有限时间内完成了任务。',tag:'JLPT N1 · 名词',related:'任務を遂行する / 計画の遂行'},
  {id:'lex-ja-n1-kyoyou',word:'許容',pronunciation:'きょよう',meaning:'容许；允许范围',example:'多少の誤差は許容できると考えられます。',translation:'可以认为一定程度的误差是可以接受的。',tag:'JLPT N1 · 名词·动词',related:'許容する / 許容範囲'},
  {id:'lex-ja-n1-ichijirushii',word:'著しい',pronunciation:'いちじるしい',meaning:'显著的；明显的',example:'この地域では人口の減少が著しいです。',translation:'这个地区人口减少十分显著。',tag:'JLPT N1 · 形容词',related:'著しい変化 / 著しい成長'},
  {id:'lex-ja-n1-manugareru',word:'免れる',pronunciation:'まぬがれる',meaning:'免于；摆脱',example:'早い対応によって大きな被害を免れました。',translation:'由于及时应对，避免了重大损失。',tag:'JLPT N1 · 动词',related:'被害を免れる / 責任を免れる'},
  {id:'lex-ja-n1-misueru',word:'見据える',pronunciation:'みすえる',meaning:'着眼于；展望',example:'将来を見据えて今から準備を進めます。',translation:'着眼于未来，从现在开始推进准备。',tag:'JLPT N1 · 动词',related:'将来を見据える / 先を見据える'},
 ],
 en:[
  {id:'lex-en-a1-time',word:'time',pronunciation:'/taɪm/',meaning:'时间',example:'Do you have time after class?',translation:'下课后你有时间吗？',tag:'A1 · noun',related:'have time / on time'},
  {id:'lex-en-a1-person',word:'person',pronunciation:'/ˈpɜː.sən/',meaning:'人',example:'She is a very kind person.',translation:'她是一个很友善的人。',tag:'A1 · noun',related:'one person / in person'},
  {id:'lex-en-a1-child',word:'child',pronunciation:'/tʃaɪld/',meaning:'孩子',example:'The child is reading a book.',translation:'那个孩子正在读书。',tag:'A1 · noun',related:'young child / only child'},
  {id:'lex-en-a1-work',word:'work',pronunciation:'/wɜːk/',meaning:'工作；工作内容',example:'I start work at nine.',translation:'我九点开始工作。',tag:'A1 · noun·verb',related:'go to work / at work'},
  {id:'lex-en-a1-shop',word:'shop',pronunciation:'/ʃɒp/',meaning:'商店',example:'There is a small shop near my home.',translation:'我家附近有一家小商店。',tag:'A1 · noun',related:'go to the shop / coffee shop'},
  {id:'lex-en-a1-train',word:'train',pronunciation:'/treɪn/',meaning:'火车；列车',example:'I go to school by train.',translation:'我坐火车去学校。',tag:'A1 · noun',related:'take a train / train station'},
  {id:'lex-en-a1-car',word:'car',pronunciation:'/kɑː/',meaning:'汽车',example:'Her car is outside the house.',translation:'她的车停在房子外面。',tag:'A1 · noun',related:'drive a car / by car'},
  {id:'lex-en-a1-drink',word:'drink',pronunciation:'/drɪŋk/',meaning:'喝；饮料',example:'I drink water every morning.',translation:'我每天早上喝水。',tag:'A1 · verb·noun',related:'drink water / a cold drink'},
  {id:'lex-en-a1-meet',word:'meet',pronunciation:'/miːt/',meaning:'见面；遇见',example:'I will meet my friend at the station.',translation:'我会在车站见朋友。',tag:'A1 · verb',related:'meet a friend / nice to meet you'},
  {id:'lex-en-a1-come',word:'come',pronunciation:'/kʌm/',meaning:'来',example:'Can you come to my house tomorrow?',translation:'你明天能来我家吗？',tag:'A1 · verb',related:'come home / come with me'},
  {id:'lex-en-a2-plan',word:'plan',pronunciation:'/plæn/',meaning:'计划',example:'We made a plan for the weekend.',translation:'我们制定了周末计划。',tag:'A2 · noun·verb',related:'make a plan / travel plan'},
  {id:'lex-en-a2-travel',word:'travel',pronunciation:'/ˈtræv.əl/',meaning:'旅行',example:'I want to travel by train this summer.',translation:'今年夏天我想坐火车旅行。',tag:'A2 · verb·noun',related:'travel abroad / travel by train'},
  {id:'lex-en-a2-choose',word:'choose',pronunciation:'/tʃuːz/',meaning:'选择',example:'You can choose any seat you like.',translation:'你可以选择任何你喜欢的座位。',tag:'A2 · verb',related:'choose a place / choose between'},
  {id:'lex-en-a2-learn',word:'learn',pronunciation:'/lɜːn/',meaning:'学习；学会',example:'I am learning how to cook.',translation:'我正在学习做饭。',tag:'A2 · verb',related:'learn a language / learn from'},
  {id:'lex-en-a2-remember',word:'remember',pronunciation:'/rɪˈmem.bə/',meaning:'记得',example:'Remember to bring your ticket.',translation:'记得带上你的票。',tag:'A2 · verb',related:'remember to do / remember a name'},
  {id:'lex-en-a2-forget',word:'forget',pronunciation:'/fəˈɡet/',meaning:'忘记',example:'I forgot my umbrella at home.',translation:'我把伞忘在家里了。',tag:'A2 · verb',related:'forget to do / forget a name'},
  {id:'lex-en-a2-busy',word:'busy',pronunciation:'/ˈbɪz.i/',meaning:'忙的',example:'I am busy this afternoon.',translation:'我今天下午很忙。',tag:'A2 · adjective',related:'busy day / be busy with'},
  {id:'lex-en-a2-possible',word:'possible',pronunciation:'/ˈpɒs.ə.bəl/',meaning:'可能的；可行的',example:'Is it possible to change the time?',translation:'可以改时间吗？',tag:'A2 · adjective',related:'if possible / as soon as possible'},
  {id:'lex-en-a2-ready',word:'ready',pronunciation:'/ˈred.i/',meaning:'准备好的',example:'Dinner is ready.',translation:'晚饭准备好了。',tag:'A2 · adjective',related:'be ready / get ready'},
  {id:'lex-en-a2-problem',word:'problem',pronunciation:'/ˈprɒb.ləm/',meaning:'问题；困难',example:'We had a small problem with the bus.',translation:'我们的公交车出了个小问题。',tag:'A2 · noun',related:'solve a problem / no problem'},
  {id:'lex-en-b1-advantage',word:'advantage',pronunciation:'/ədˈvɑːn.tɪdʒ/',meaning:'优势；好处',example:'One advantage of studying online is flexibility.',translation:'在线学习的一个好处是灵活。',tag:'B1 · noun',related:'main advantage / have an advantage'},
  {id:'lex-en-b1-benefit',word:'benefit',pronunciation:'/ˈben.ɪ.fɪt/',meaning:'益处；使受益',example:'Regular practice has many benefits.',translation:'规律练习有很多好处。',tag:'B1 · noun·verb',related:'benefit from / health benefit'},
  {id:'lex-en-b1-behaviour',word:'behaviour',pronunciation:'/bɪˈheɪ.vjə/',meaning:'行为',example:'Small changes in behaviour can become habits.',translation:'行为上的小改变可以逐渐成为习惯。',tag:'B1 · noun',related:'change behaviour / user behaviour'},
  {id:'lex-en-b1-environment',word:'environment',pronunciation:'/ɪnˈvaɪ.rən.mənt/',meaning:'环境',example:'A quiet environment helps me concentrate.',translation:'安静的环境帮助我集中注意力。',tag:'B1 · noun',related:'learning environment / natural environment'},
  {id:'lex-en-b1-respond',word:'respond',pronunciation:'/rɪˈspɒnd/',meaning:'回应；作出反应',example:'She responded quickly to my message.',translation:'她很快回复了我的消息。',tag:'B1 · verb',related:'respond to / respond quickly'},
  {id:'lex-en-b1-describe',word:'describe',pronunciation:'/dɪˈskraɪb/',meaning:'描述',example:'Can you describe what happened?',translation:'你能描述一下发生了什么吗？',tag:'B1 · verb',related:'describe a situation / describe clearly'},
  {id:'lex-en-b1-influence',word:'influence',pronunciation:'/ˈɪn.flu.əns/',meaning:'影响',example:'Friends can influence the way we think.',translation:'朋友会影响我们的思考方式。',tag:'B1 · noun·verb',related:'influence a decision / strong influence'},
  {id:'lex-en-b1-attempt',word:'attempt',pronunciation:'/əˈtempt/',meaning:'尝试',example:'My first attempt was not successful, but I learned a lot.',translation:'我的第一次尝试没有成功，但我学到了很多。',tag:'B1 · noun·verb',related:'make an attempt / attempt to do'},
  {id:'lex-en-b1-reduce',word:'reduce',pronunciation:'/rɪˈdjuːs/',meaning:'减少',example:'Walking every day can reduce stress.',translation:'每天走路可以减轻压力。',tag:'B1 · verb',related:'reduce costs / reduce stress'},
  {id:'lex-en-b1-increase',word:'increase',pronunciation:'/ɪnˈkriːs/',meaning:'增加',example:'Reading regularly can increase your vocabulary.',translation:'规律阅读可以扩大词汇量。',tag:'B1 · verb·noun',related:'increase by / increase the chance'},
  {id:'lex-en-b2-outcome',word:'outcome',pronunciation:'/ˈaʊt.kʌm/',meaning:'结果；成果',example:'The outcome depended on several factors.',translation:'结果取决于几个因素。',tag:'B2 · noun',related:'likely outcome / positive outcome'},
  {id:'lex-en-b2-implement',word:'implement',pronunciation:'/ˈɪm.plɪ.ment/',meaning:'实施；执行',example:'The team implemented the new plan gradually.',translation:'团队逐步实施了新计划。',tag:'B2 · verb',related:'implement a plan / implement changes'},
  {id:'lex-en-b2-allocate',word:'allocate',pronunciation:'/ˈæl.ə.keɪt/',meaning:'分配',example:'We need to allocate more time to testing.',translation:'我们需要给测试分配更多时间。',tag:'B2 · verb',related:'allocate time / allocate resources'},
  {id:'lex-en-b2-objective',word:'objective',pronunciation:'/əbˈdʒek.tɪv/',meaning:'目标；客观的',example:'Our main objective is to improve reliability.',translation:'我们的主要目标是提升可靠性。',tag:'B2 · noun·adjective',related:'main objective / objective evidence'},
  {id:'lex-en-b2-bias',word:'bias',pronunciation:'/ˈbaɪ.əs/',meaning:'偏见；偏差',example:'The study tried to reduce selection bias.',translation:'这项研究试图减少选择偏差。',tag:'B2 · noun',related:'confirmation bias / reduce bias'},
  {id:'lex-en-b2-valid',word:'valid',pronunciation:'/ˈvæl.ɪd/',meaning:'有效的；合理的',example:'That is a valid concern.',translation:'这是一个合理的担忧。',tag:'B2 · adjective',related:'valid reason / valid evidence'},
  {id:'lex-en-b2-consistent',word:'consistent',pronunciation:'/kənˈsɪs.tənt/',meaning:'一致的；稳定的',example:'The results are consistent with earlier research.',translation:'结果与早期研究一致。',tag:'B2 · adjective',related:'consistent with / consistent performance'},
  {id:'lex-en-b2-sufficient',word:'sufficient',pronunciation:'/səˈfɪʃ.ənt/',meaning:'足够的',example:'We do not have sufficient evidence yet.',translation:'我们目前还没有足够的证据。',tag:'B2 · adjective',related:'sufficient time / sufficient evidence'},
  {id:'lex-en-b2-obtain',word:'obtain',pronunciation:'/əbˈteɪn/',meaning:'获得',example:'Researchers obtained similar results in both groups.',translation:'研究人员在两组中得到了相似结果。',tag:'B2 · verb',related:'obtain permission / obtain data'},
  {id:'lex-en-b2-emerge',word:'emerge',pronunciation:'/ɪˈmɜːdʒ/',meaning:'出现；显现',example:'A clear pattern began to emerge from the data.',translation:'数据中开始显现出清晰的规律。',tag:'B2 · verb',related:'emerge from / gradually emerge'},
  {id:'lex-en-c1-accountability',word:'accountability',pronunciation:'/əˌkaʊn.təˈbɪl.ə.ti/',meaning:'问责；责任制',example:'Clear ownership improves accountability.',translation:'明确责任归属能提高问责性。',tag:'C1 · noun',related:'public accountability / ensure accountability'},
  {id:'lex-en-c1-concession',word:'concession',pronunciation:'/kənˈseʃ.ən/',meaning:'让步；承认',example:'The agreement required concessions from both sides.',translation:'这项协议要求双方都作出让步。',tag:'C1 · noun',related:'make a concession / major concession'},
  {id:'lex-en-c1-discourse',word:'discourse',pronunciation:'/ˈdɪs.kɔːs/',meaning:'论述；话语',example:'Public discourse often simplifies complex issues.',translation:'公共讨论常会简化复杂问题。',tag:'C1 · noun',related:'public discourse / academic discourse'},
  {id:'lex-en-c1-empirical',word:'empirical',pronunciation:'/ɪmˈpɪr.ɪ.kəl/',meaning:'经验性的；实证的',example:'The claim is supported by empirical evidence.',translation:'这一主张得到实证证据支持。',tag:'C1 · adjective',related:'empirical evidence / empirical study'},
  {id:'lex-en-c1-formulate',word:'formulate',pronunciation:'/ˈfɔː.mjə.leɪt/',meaning:'制定；系统表达',example:'We need to formulate a clearer hypothesis.',translation:'我们需要提出一个更清晰的假设。',tag:'C1 · verb',related:'formulate a plan / formulate a hypothesis'},
  {id:'lex-en-c1-inherent',word:'inherent',pronunciation:'/ɪnˈher.ənt/',meaning:'固有的；内在的',example:'There is inherent uncertainty in every forecast.',translation:'每个预测都存在固有的不确定性。',tag:'C1 · adjective',related:'inherent risk / inherent limitation'},
  {id:'lex-en-c1-precedent',word:'precedent',pronunciation:'/ˈpres.ɪ.dənt/',meaning:'先例',example:'The ruling could set an important precedent.',translation:'这一裁决可能树立重要先例。',tag:'C1 · noun',related:'set a precedent / historical precedent'},
  {id:'lex-en-c1-rigorous',word:'rigorous',pronunciation:'/ˈrɪɡ.ər.əs/',meaning:'严谨的；严格的',example:'The method requires rigorous testing.',translation:'这种方法需要严谨的测试。',tag:'C1 · adjective',related:'rigorous analysis / rigorous standard'},
  {id:'lex-en-c1-synthesize',word:'synthesize',pronunciation:'/ˈsɪn.θə.saɪz/',meaning:'综合；合成',example:'The report synthesizes findings from several studies.',translation:'这份报告综合了多项研究的发现。',tag:'C1 · verb',related:'synthesize information / synthesize evidence'},
  {id:'lex-en-c1-tentative',word:'tentative',pronunciation:'/ˈten.tə.tɪv/',meaning:'暂定的；试探性的',example:'The team reached a tentative conclusion.',translation:'团队得出了一个暂定结论。',tag:'C1 · adjective',related:'tentative conclusion / tentative agreement'},
  {id:'lex-en-c2-albeit',word:'albeit',pronunciation:'/ɔːlˈbiː.ɪt/',meaning:'尽管；虽然',example:'The proposal is promising, albeit difficult to implement.',translation:'这项提议很有前景，尽管实施起来很困难。',tag:'C2 · conjunction',related:'albeit briefly / albeit imperfectly'},
  {id:'lex-en-c2-ostensibly',word:'ostensibly',pronunciation:'/ɒˈsten.sə.bli/',meaning:'表面上；据称',example:'The policy was ostensibly designed to increase fairness.',translation:'该政策表面上旨在提高公平性。',tag:'C2 · adverb',related:'ostensibly simple / ostensibly intended'},
  {id:'lex-en-c2-pervasive',word:'pervasive',pronunciation:'/pəˈveɪ.sɪv/',meaning:'普遍存在的；无处不在的',example:'The influence of digital media is pervasive.',translation:'数字媒体的影响无处不在。',tag:'C2 · adjective',related:'pervasive influence / pervasive problem'},
  {id:'lex-en-c2-delineate',word:'delineate',pronunciation:'/dɪˈlɪn.i.eɪt/',meaning:'界定；描绘',example:'The report clearly delineates the limits of the study.',translation:'报告清楚界定了研究的局限。',tag:'C2 · verb',related:'delineate boundaries / clearly delineate'},
  {id:'lex-en-c2-incontrovertible',word:'incontrovertible',pronunciation:'/ˌɪn.kɒn.trəˈvɜː.tə.bəl/',meaning:'无可争辩的',example:'The evidence is strong, but not incontrovertible.',translation:'证据很强，但并非无可争辩。',tag:'C2 · adjective',related:'incontrovertible evidence / incontrovertible fact'},
  {id:'lex-en-c2-recalcitrant',word:'recalcitrant',pronunciation:'/rɪˈkæl.sɪ.trənt/',meaning:'顽固抗拒的；难处理的',example:'The reform struggled against recalcitrant institutions.',translation:'改革在顽固抗拒的机构面前推进艰难。',tag:'C2 · adjective',related:'recalcitrant problem / recalcitrant opposition'},
  {id:'lex-en-c2-trenchant',word:'trenchant',pronunciation:'/ˈtren.tʃənt/',meaning:'尖锐有力的；犀利的',example:'She offered a trenchant critique of the argument.',translation:'她对这一论点提出了犀利的批评。',tag:'C2 · adjective',related:'trenchant critique / trenchant observation'},
  {id:'lex-en-c2-circumscribe',word:'circumscribe',pronunciation:'/ˈsɜː.kəm.skraɪb/',meaning:'限制；划定范围',example:'The court sought to circumscribe the agency’s authority.',translation:'法院试图限制该机构的权限范围。',tag:'C2 · verb',related:'circumscribe authority / tightly circumscribed'},
  {id:'lex-en-c2-epistemic',word:'epistemic',pronunciation:'/ˌep.ɪˈstiː.mɪk/',meaning:'认识论的；与知识有关的',example:'The debate concerns epistemic uncertainty rather than missing data alone.',translation:'这场争论涉及认识层面的不确定性，而不只是数据缺失。',tag:'C2 · adjective',related:'epistemic uncertainty / epistemic limits'},
  {id:'lex-en-c2-parsimonious',word:'parsimonious',pronunciation:'/ˌpɑː.sɪˈməʊ.ni.əs/',meaning:'简约的；过分节俭的',example:'A parsimonious explanation accounts for the evidence with few assumptions.',translation:'简约的解释用较少假设说明现有证据。',tag:'C2 · adjective',related:'parsimonious model / parsimonious explanation'},
 ],
};

export function expandedCoreWords(language:Language,level:string):Word[]{
 return coreVocabularyExpansion[language].filter(word=>new RegExp(`\\b${level}\\b`).test(word.tag));
}
