/* Requires a running app, an owner session, and Playwright. No production authentication bypass. */
import {chromium} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
const origin=process.env.APP_URL??'http://localhost:3000';
const stateFile=process.env.OWNER_STORAGE_STATE;
if(!stateFile)throw new Error('Provide OWNER_STORAGE_STATE from a real owner login; do not commit this credential file.');
const browser=await chromium.launch({headless:true});
const viewports=[{width:360,height:800},{width:375,height:812},{width:390,height:844},{width:412,height:915},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1366,height:768},{width:1440,height:900},{width:1920,height:1080}];
const pages=['Today','Learn','Library','Vocabulary','Grammar','Reading','Listening','Speaking','Review','Progress','AI Tutor','My Sentences','Mistake Notebook','Settings','Profile'];
await mkdir('qa-artifacts',{recursive:true});const results=[];
try{for(const viewport of viewports){const {width,height}=viewport;const context=await browser.newContext({viewport,storageState:stateFile});const page=await context.newPage();for(const name of pages){await page.goto(`${origin}/#${encodeURIComponent(name)}`);await page.waitForSelector('.app-shell');await page.waitForTimeout(300);const result=await page.evaluate(()=>{const root=document.documentElement;const overflow=root.scrollWidth>root.clientWidth+1;const visible=el=>{const r=el.getBoundingClientRect();return r.width>0&&r.height>0&&getComputedStyle(el).visibility!=='hidden'};const sidebar=document.querySelector('.sidebar'),bottom=document.querySelector('.bottom-nav');const tiny=window.innerWidth<640?[...document.querySelectorAll('button')].filter(visible).filter(el=>{const r=el.getBoundingClientRect();return r.width<43||r.height<43}).map(el=>({label:el.getAttribute('aria-label')||el.textContent?.trim().slice(0,35),width:Math.round(el.getBoundingClientRect().width),height:Math.round(el.getBoundingClientRect().height)})):[];return {overflow,sidebarVisible:sidebar&&visible(sidebar),bottomVisible:bottom&&visible(bottom),tinyTargets:tiny}});results.push({width,height,page:name,...result});await writeFile('qa-artifacts/responsive-report.json',JSON.stringify(results,null,2));if(result.tinyTargets.length)throw new Error(`${name} has undersized mobile touch targets: ${JSON.stringify(result.tinyTargets)}`);if(result.overflow)throw new Error(`${name} overflows at ${width}px`);if(width<640&&result.sidebarVisible)throw new Error(`Desktop sidebar visible on mobile`);if(name==='Today'&&width<640){const cta=page.getByRole('button',{name:/Start today’s session|Continue session|开始今日学习|继续学习/});const box=await cta.boundingBox();if(!box||box.y+box.height>height)throw new Error('Daily CTA not in first screen');}if(width===390||width===1440)await page.screenshot({path:`qa-artifacts/${width}-${name.replaceAll(' ','-')}.png`,fullPage:true});}await context.close();}await writeFile('qa-artifacts/responsive-report.json',JSON.stringify(results,null,2));}finally{await browser.close()}
console.log(`Checked ${viewports.length*pages.length} page/viewport combinations. Review tiny-target results and screenshots before release.`);
